### ISSUE TITLE
error when deploying object cluster 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1029]
### Scenario
- install orchestrator environment using the autosetup.py script from alpha-8 branch
- deploy object cluster

### ays error
```
2017-09-13 13:37:49,842 - ...s9/JumpScale9AYS/jobcontroller/Job.py:56 - ERROR    - Traceback (most recent call last):
  File "/opt/jumpscale9/lib/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/c931ec2f538ceb9dc588876e075d0748.py", line 480, in install
    save_config(job)
  File "/tmp/actions/storage_cluster/c931ec2f538ceb9dc588876e075d0748.py", line 57, in save_config
    iyo_org = aysconfig["iyo_org"]
KeyError: 'iyo_org'
```

### software version
1.1.0-alpha-8

**Comment by FastGeert** [comment]
Issue does not exist in beta-1, need to backport a small fix

**Comment by maxux** [comment]
Cherry picked to `1.1.0-alpha-8`

**Comment by ahmedelsayed-93** [comment]
### software version
1.1.0-alpha-8 c66d462
