### ISSUE TITLE
Can't create object cluster 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1050]
## Issue 
create object cluster with the following payload : 
```
{
	"label": "ob",
	"servers": 2,
	"driveType": "hdd",
	"metaDriveType": "ssd",
	"nodes": [
		"0cc47a740646",
		"0cc47a740632"
	],
	"clusterType": "object",
	"dataShards": 1,
	"parityShards": 1
}
```
it results the following error :
```
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/08e87e33f06b628e614ff865f396866f.py", line 288, in init
    metadisk = metadisks[nodename][idx]
IndexError: list index out of range
[Mon18 08:03] - ays_api.py          :519 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 list index out of range
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 505, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 154, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 518, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 143, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/08e87e33f06b628e614ff865f396866f.py", line 288, in init
    metadisk = metadisks[nodename][idx]
IndexError: list index out of range
```
## Software Version 
1.1.0-alpha-8 on 7efbde19b12fbf2e1ba8c2cf43e67ce03231b223

**Comment by khaledkbadr** [comment]
Fixed in https://github.com/zero-os/0-orchestrator/commit/95169a2f3e3711b6daa39ec14a8a510eb4656e29

**Comment by Dinaamagdy** [comment]
## Software version 
95169a2f3e3711b6daa39ec14a8a510eb4656e29
