### ISSUE TITLE
Fail to remove a storage cluster that failed to create

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#1084]
'''python
WARNING:asyncio:Executing <Handle Task._wakeup created at /usr/lib/python3.5/asyncio/futures.py:373> took 0.212 seconds
[Tue26 10:04] - Job.py              :57  :j.core.jobcontroller.job.8dfe3721e6ede234799f9db9d8a72871 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/a30d49e72a959e3670cc36b4079bd8b5.py", line 405, in stop
    cluster = get_cluster(job)
  File "/tmp/actions/storage_cluster/a30d49e72a959e3670cc36b4079bd8b5.py", line 132, in get_cluster
    return StorageCluster.from_ays(job.service, job.context['token'])
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 38, in from_ays
    storages_server = StorageServer.from_ays(storageEngine_service, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 160, in from_ays
    storageEngine = StorageEngine.from_ays(storageEngine_services, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageEngine.py", line 30, in from_ays
    container = Container.from_ays(service.parent, password, logger=service.logger)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 110, in from_ays
    sp = node.storagepools.get(fs_service.parent.name)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 59, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name cluster_2c600ccd2ae9_primary_sda
[Tue26 10:04] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Tue26 10:04] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run 47f3a22ab320066a7d817b74e5f99217
Error of job: storage_cluster!primary (stop):
*TRACEBACK*********************************************************************************
ValueError: Could not find StoragePool with name cluster_2c600ccd2ae9_primary_sda

******************************************************************************************
'''

**Comment by khaledkbadr** [comment]
I fixed the above error in https://github.com/zero-os/0-orchestrator/pull/1349, but when I tried to test the behavior I hit https://github.com/Jumpscale/ays9/issues/376 issue, which ays known issue. So this issue still not resolved completely and blocked on ays's behavior
