### ISSUE TITLE
Need to specify type of lacking disks

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#1095]
![image](https://user-images.githubusercontent.com/15246294/30915696-de447002-a397-11e7-9065-3889f1a54128.png)

**Comment by ahmedelsayed-93** [comment]
api returns internal server error 
![image](https://user-images.githubusercontent.com/24386820/32698609-eb2bbf7c-c7b0-11e7-848c-a4727af56d2c.png)

### ays log
```
[Sun12 11:53] - ays_api.py          :555 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 Not enough available ssd disks on node 0cc47a740636
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 541, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 154, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 533, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 35, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 28, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 144, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 677, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110832)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114026)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storagecluster.object/1d1545a84ff15bc53f0f2828b4c7f2eb.py", line 335, in init
    datadisks, metadisks = storagecluster_sal.get_disks(data_available_disks, meta_available_disks)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 118, in get_disks
    datadisks = self._get_disks_from_map(diskmap[self.data_disk_type], data_disks_per_node, self.data_disk_type)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 127, in _get_disks_from_map
    raise ValueError("Not enough available {} disks on node {}".format(disktype, node))
ValueError: Not enough available ssd disks on node 0cc47a740636

```
