### ISSUE TITLE
error when create object cluster

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1098]
### software versions
orchestrator : flist ```https://hub.gig.tech/maxux/0-orchestrator-full-alpha-8.flist```
0-stor flist : master
#### ays log
```
RuntimeError: Failed to start zerostor server: cluster_248a07e77170_myobjectcluster_sda_stor_2000
2017-09-27 13:39:47,486 - ...s9/JumpScale9AYS/jobcontroller/Job.py:56 - ERROR    - Traceback (most recent call last):
  File "/opt/jumpscale9/lib/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/zerostor/e5ccacb02bde71a9706f1b0439004f71.py", line 18, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/opt/jumpscale9/lib/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/opt/jumpscale9/lib/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/jumpscale9/lib/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/opt/jumpscale9/lib/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/opt/jumpscale9/lib/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/opt/jumpscale9/lib/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/jumpscale9/lib/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/zerostor/e5ccacb02bde71a9706f1b0439004f71.py", line 157, in start
    storageEngine.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/ZeroStor.py", line 66, in start
    raise RuntimeError('Failed to start zerostor server: {}'.format(self.name))

```

**Comment by zaibon** [comment]
Need more informations.

How did you tried to install the object cluster, the arguments used. Version of 0-os,...

**Comment by ahmedelsayed-93** [comment]
it was fixed by updating the flist ```https://hub.gig.tech/maxux/0-orchestrator-full-alpha-8.flist``` to the latest changes on alpha-8 branch
