### ISSUE TITLE
internal server error when create gateway with httpproxies 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1102]
### steps
- create gateway with httpproxy

### ays error
```
[Thu28 08:37] - Job.py              :56  :j.core.jobcontroller.job.322e3408bcb946cd37ceef3627b477db - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/52f002a5d77aee47fb08723fbaea5588.py", line 384, in install
    j.tools.async.wrappers.sync(service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/52f002a5d77aee47fb08723fbaea5588.py", line 252, in start
    j.tools.async.wrappers.sync(http.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/http/fc88f0b4069451a202874f277dd9aa16.py", line 107, in start
    apply_rules(job, httpproxies)
  File "/tmp/actions/http/fc88f0b4069451a202874f277dd9aa16.py", line 162, in apply_rules
    http.apply_rules()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/gateway/http.py", line 26, in apply_rules
    raise RuntimeError("Failed to start caddy server")
RuntimeError: Failed to start caddy server
```
### software version
1.1.0-alpha-8 : ffcdcb98d

**Comment by zaibon** [comment]
@ahmedelsayed-93 What's the status of this ?
