### ISSUE TITLE
 ays sometimes executes old services

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#114]
### Scenario
1-  i removed /optvar/log/jumpscale.log content
2- then i called API 
```POST nodes/{nodeis}/vms``` and the response was 201 created 

### ays log
```
2017-04-21 07:00:53,197 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,200 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,204 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,208 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,212 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,215 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,219 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,223 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,226 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,230 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,234 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,237 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,241 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,245 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,249 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,253 - ...aselib/atyourservice81/lib/Service.py:668 - INFO     - schedule action install on service:bridge!aaa
2017-04-21 07:00:53,257 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,261 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,264 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,268 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,272 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,276 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,279 - ...aselib/atyourservice81/lib/Service.py:668 - INFO     - schedule action install on service:bridge!test
2017-04-21 07:00:53,283 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,287 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,290 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,294 - ...aselib/atyourservice81/lib/Service.py:666 - INFO     - action install already in ok state, don't schedule again
2017-04-21 07:00:53,298 - ...thon3.5/dist-packages/sanic/server.py:352 - WARNING  - Executing <Handle Task._step created at /usr/local/lib/python3.5/dist-packages/sanic/server.py:164> took 0.473 seconds
2017-04-21 07:00:53,299 - ...umpScale/baselib/jobcontroller/Job.py:70 - INFO     - job job: vm!vm1 (processChange) done sucessfuly
2017-04-21 07:00:53,332 - ...cale/baselib/jobcontroller/RunStep.py:65 - INFO     - execute job: bridge!aaa (install)
2017-04-21 07:00:53,343 - ...cale/baselib/jobcontroller/RunStep.py:65 - INFO     - execute job: bridge!test (install)
2017-04-21 07:00:53,354 - ...cale/baselib/jobcontroller/RunStep.py:65 - INFO     - execute job: bridge!aaa (delete)
2017-04-21 07:00:53,499 - ...thon3.5/dist-packages/sanic/server.py:352 - WARNING  - Executing <Handle Task._step created at /usr/local/lib/python3.5/dist-packages/sanic/server.py:164> took 0.135 seconds
2017-04-21 07:00:53,613 - ...umpScale/baselib/jobcontroller/Job.py:61 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/bridge/3634be1aad7b260a783729b23055ca5d.py", line 34, in install
    settings=service.model.data.setting.to_dict())
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 817, in create
    raise RuntimeError('failed to create bridge %s' % result.data)
RuntimeError: failed to create bridge "file exists"
2017-04-21 07:00:53,630 - ...umpScale/baselib/jobcontroller/Job.py:61 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/bridge/5707c1552ed8db44d02474e58f48d830.py", line 18, in delete
    cl.bridge.delete(service.name)
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 851, in delete
    raise RuntimeError('failed to list delete: %s' % result.data)
RuntimeError: failed to list delete: "Link not found"

```

**Comment by ahmedelsayed-93** [comment]
can't reproduce 
### SV
jumpscale : 68832ff8
grid : f100e6a

**Comment by ahmedelsayed-93** [comment]
![image](https://cloud.githubusercontent.com/assets/24386820/25796615/757c4f40-33da-11e7-930e-9718aac5d246.png)

### SV
jumpscale  68832ff
grid c1384ba

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce

**Comment by islamTaha12** [comment]
@abdulrahmantkhalifa  You have to force AYS to fail in any blueprint execution to produce an error message, then try to request any api, the response will be the error message of this bp
