### ISSUE TITLE
Deleting a halted node fails on etcd stop and ovs container stop

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-orchestrator#1147]
Deleting a halted node fails on the stop of the etcd and container services because it can't connect to the node. This needs to be hardened since the node will obviously never be reachable.
```
[Mon02 13:03] - Job.py              :56  :j.core.jobcontroller.job.4a63b493ede23bf49ebec4eb6a657778 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/etcd/ea2242c6448bfe378213619af260a586.py", line 84, in stop
    etcd = ETCD.from_ays(service, job.context['token'], logger=service.logger)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/ETCD.py", line 96, in from_ays
    container = Container.from_ays(service.parent, password, logger=service.logger)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 100, in from_ays
    node = Node.from_ays(service.parent, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 36, in from_ays
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 20, in __init__
    self._client = Client(host=addr, port=port, password=password, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2622, in __init__
    raise ConnectionError("Could not connect to remote host %s" % host)
ConnectionError: Could not connect to remote host 192.168.193.144
[Mon02 13:03] - Job.py              :56  :j.core.jobcontroller.job.9e7ef202ddb7c1380f92e58a1b729d7b - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/49e97241ffacf8e707a2b04b3601d094.py", line 101, in stop
    container = Container.from_ays(job.service, job.context['token'], logger=job.service.logger)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 100, in from_ays
    node = Node.from_ays(service.parent, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 36, in from_ays
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 20, in __init__
    self._client = Client(host=addr, port=port, password=password, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2622, in __init__
    raise ConnectionError("Could not connect to remote host %s" % host)
ConnectionError: Could not connect to remote host 192.168.193.144
```

**Comment by rkhamis** [comment]
Same as #1146 , we need to make the client a lazy loading property of sal/Node

**Comment by serboctor** [comment]
Task to refactor Sal modules https://github.com/zero-os/0-orchestrator/issues/1188
