### ISSUE TITLE
cann't run node.bp  

### ISSUE THREAD

**Issue by ashraffouda** [zero-os/0-orchestrator#1174]
node.bp
```
network.zero-os__storage:
  vlanTag: 101
  cidr: "172.17.0.0/16"

node.zero-os__54a338471b91:
  redisAddr: 192.168.122.194
  redisPort: 6379
  hostname: "myg8os1"
  networks:
  - 'storage'


actions:
 - action: install
```

```
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storagepool/c8c3dcb120f03c25c7fc8a2f2907d01f.py", line 59, in install
    updateDevices(service, pool, devices)
  File "/tmp/actions/storagepool/c8c3dcb120f03c25c7fc8a2f2907d01f.py", line 226, in updateDevices
    pool.device_add(*extradevices)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/StoragePool.py", line 140, in device_add
    part = _prepare_device(self.node, device)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/StoragePool.py", line 19, in _prepare_device
    raise ValueError("device {} not found".format(name))
ValueError: device vdf1 not found
[Sun08 15:40] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 3: error
[Sun08 15:40] - Run.py              :118 :j.atyourservice.server         - ERROR    - error during execution of step 3 in run 3d3226a17164e3b2f3e9e85d226d0d22
Error of job: storagepool!54a338471b91_fscache (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storagepool/c8c3dcb120f03c25c7fc8a2f2907d01f.py", line 59, in install
    updateDevices(service, pool, devices)
  File "/tmp/actions/storagepool/c8c3dcb120f03c25c7fc8a2f2907d01f.py", line 226, in updateDevices
    pool.device_add(*extradevices)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/StoragePool.py", line 140, in device_add
    part = _prepare_device(self.node, device)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/StoragePool.py", line 19, in _prepare_device
    raise ValueError("device {} not found".format(name))
ValueError: device vdf1 not found
```

**Comment by serboctor** [comment]
I can't reproduce it even though I use the same script to create the qemu node. I destroy/install everyday and it works just fine.
