### ISSUE TITLE
vms_apis : shutdown vm api doesn't work

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#128]
### API
```POST /nodes/{nodeid}/vms/{vmid}/shutdown```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25431569/6f7df042-2a81-11e7-98b3-0ec1c561f700.png)

### Actual result

**grid api resppnse**

![image](https://cloud.githubusercontent.com/assets/24386820/25431598/8733d31e-2a81-11e7-9b6e-2d1fbbb485ac.png)

**python client response**

![image](https://cloud.githubusercontent.com/assets/24386820/25431626/a1b148d4-2a81-11e7-84e0-606a4f7f166c.png)

**Comment by serboctor** [comment]
The shutdown action wasn't implemented so I added its implementation. However, shuting down a vm that doesn't have a disk and os on it will result in nothing even with my implementation.

**Comment by ahmedelsayed-93** [comment]
### error when trying to shutdown vm
### ays log
```
Mon15 14:27] - Job.py              :63  :j.jobcontroller.job.05c64f55c43ce7edf6623dd15b5c5e92 - INFO     - job job: bootstrap.g8os!grid1 (bootstrap) done sucessfuly
[Mon15 14:27] - Job.py              :54  :j.jobcontroller.job.9e03e53a163a30eb3a6944d31259ccc7 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/111c40417838c44657fe1e3cbc54a613.py", line 335, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JSExceptions.RuntimeError: ERROR: Failed to shutdown vm vm2 ((type:runtime.error)
[Mon15 14:27] - RunStep.py          :84  :j.atyourservice                - INFO     - runstep 1: error
[Mon15 14:27] - Run.py              :108 :j.atyourservice                - ERROR    - error during execution of step 1 in run 5209d3f26327a586eaa9639430a0ffa7
Error of job: vm!vm2 (shutdown):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/111c40417838c44657fe1e3cbc54a613.py", line 335, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JSExceptions.RuntimeError: ERROR: Failed to shutdown vm vm2 ((type:runtime.error)


******************************************************************************************
```

and the status of the vm was **halting**
![image](https://cloud.githubusercontent.com/assets/24386820/26062661/ca254c8e-398b-11e7-9002-2708cb877194.png)

**Comment by islamTaha12** [comment]
Re-open

**Branch**
Master branch update till 1.1.0-alpha-3

```bash 
 File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/e65a399f1867cac6b4ad4b83dbd3bcf3.py", line 160, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JSExceptions.RuntimeError: ERROR: Failed to shutdown vm 4043e7f347 ((type:runtime.error)
[Tue23 16:42] - RunStep.py          :84  :j.atyourservice                - INFO     - runstep 1: error
[Tue23 16:42] - Run.py              :108 :j.atyourservice                - ERROR    - error during execution of step 1 in run 8089b3853633973ffb7b599f405cf504
Error of job: vm!4043e7f347 (shutdown):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/e65a399f1867cac6b4ad4b83dbd3bcf3.py", line 160, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JSExceptions.RuntimeError: ERROR: Failed to shutdown vm 4043e7f347 ((type:runtime.error)


******************************************************************************************
```

**Comment by grimpy** [comment]
@islamTaha12  Which template was used?

**Comment by islamTaha12** [comment]
@grimpy 
ardb://hub.gig.tech:16379/template:ubuntu-1604

**Comment by grimpy** [comment]
Please validate first that the vm got properly booted and then try the shutdown api.

**Comment by Dinaamagdy** [comment]
can't verify due to : 
https://github.com/zero-os/0-orchestrator/issues/298

**Comment by grimpy** [comment]
That's not true, cause #298 happens but the rescheduling of AYS makes it eventually work (the start of vm that is)

**Comment by Dinaamagdy** [comment]
## Steps : 
- after make sure that status of vm is running .
- try to shutdown it 

## Response : 
status of vm be halting then error and  ays give this error : 
![selection_389](https://cloud.githubusercontent.com/assets/24386802/26821702/9f7edc66-4aa7-11e7-9323-6939a0fcaf1a.png)

**Comment by grimpy** [comment]
Please prove to me you get a vm running with the os booted

**Comment by Dinaamagdy** [comment]
## Software Version
e6c8b485e8666e342109bd9748f9b17d594496b2
