### ISSUE TITLE
Post storage pool doesn't return response when giving wrong params.

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#1305]
1- Create Storagepool with raid0 and one device, this scenario is wrong and it returns error in ays which is expected  .. but it doesn't return response 
![scsh1](https://user-images.githubusercontent.com/15011431/32211871-3ec42392-be1d-11e7-9842-84f9975d6e4e.png)

#### AYS error
[Tue31 07:17] - Run.py              :162 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run 7879bcf5de478a1d695cab5fa07ee5d0
Error of job: storagepool!test33 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/tmp/actions/storagepool/2f7aa99d8e7ce1a40021771b72462f35.py", line 145, in install
    pool = node.storagepools.get(name)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 61, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name test33

During handling of the above exception, another exception occurred:

zeroos.core0.client.client.ResultError: "(ERROR): [btrfs-progs v4.8\nSee http://btrfs.wiki.kernel.org for more information.\n ERROR: unable to create FS with metadata profile RAID0 (have 1 de
vices but 2 devices are required)\n]"

******************************************************************************************

2- Also the 202 in the docs should be changed to 201 
![scscsc](https://user-images.githubusercontent.com/15011431/32212056-e681b43c-be1d-11e7-9974-0745a524ab45.png)

**Comment by serboctor** [comment]
The orchestrator api waits for all 6 retries of ays if an error ocurs. That's why it won't return an error immediately until all 6 retries are done.
