### ISSUE TITLE
statsdb service error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1355]
### ays log
```
[Mon13 10:30] - Job.py              :70  :j.core.jobcontroller.job.c416c367ae4b0df3f285c271f03a185b - ERROR    - job: node.zero-os!0cc47a740636 (monitor) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.zero-os/6814a46aa4d8eb5145fb2fabd74080ce.py", line 36, in monitor
    and statsdb_service.model.data.status == 'running'):
AttributeError: 'NoneType' object has no attribute 'model'
```
### software version
master 851d41fa

**Comment by rkhamis** [comment]
this [line](https://github.com/zero-os/0-orchestrator/blob/master/templates/node.zero-os/actions.py) should be hardened to check `if statsdb_service` as well
