### ISSUE TITLE
Performance test script

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#188]
Performance test using the ndbserver, using a container next to the nbdserver which has fio and the correct nbdclient to run the test.

```
~/tests/bd-performance.py [resourcepool api] [storagecluster name] [vdisk count] [vdisk size] [run time]
  resourcepool api: url to the resource pool api server
  storagecluster name: name of the storage cluster in which the vdisks need to be created
  vdisk count: number of vdisks that need to be created
  vdisk size: size of the vdisks in GB
  run time: time fio should be run 
```

**Comment by Dinaamagdy** [comment]
Script give this error now :

```
raceback (most recent call last):
  File "/tmp/bd-perf.py", line 53, in test_fio_nbd
    deployInfo = deploy(api, nodeIDs, nodeIPs, restapiserver, storagecluster, vdiskcount, vdisksize, vdisktype)
  File "/tmp/bd-perf.py", line 177, in deploy
    storageclusterInfo=storageclusterInfo)
  File "/tmp/bd-perf.py", line 246, in startNbd
    api.nodes.FileUpload(containername=containername,
  File "/home/dina/.local/lib/python3.5/site-packages/zeroos/orchestrator/client/nodes_service.py", line 85, in FileUpload
    return self.client.post(uri, data, headers, query_params, content_type)
  File "/home/dina/.local/lib/python3.5/site-packages/zeroos/orchestrator/client/client.py", line 47, in post
    res.raise_for_status()
  File "/home/dina/.local/lib/python3.5/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://10.147.17.26:8080/nodes/248a07e77210/containers/nbd_14967606615286107/filesystem?path=%2Fnbd_14967606615286107.config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bd-perf.py", line 359, in <module>
    test_fio_nbd()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/bd-perf.py", line 57, in test_fio_nbd
    raise RuntimeError(e)
RuntimeError: 400 Client Error: Bad Request for url: http://10.147.17.26:8080/nodes/248a07e77210/containers/nbd_14967606615286107/filesystem?path=%2Fnbd_14967606615286107.config

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Dinaamagdy** [comment]
## Software Version 
42bd7ade26421f525e665abfeb1d7d19b8143a37
