### ISSUE TITLE
Cannot delete storagecluster

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#260]
#### Environment
be-g8-3, jumpscale 8.2.0.rc1, resourcepool 1.1.0-alpha-2, g8os master-screen-size

#### How i got in this situation
After running the performance tests for a while i decided to reboot all nodes because i had some trouble with ndb-client.
When the nodes were back up, i launched another performance test, which still had troubles with ndb-client. Then i decided to delete the storagecluster, to re-setup again.

#### Stacktrace i got in rest result
```
{
  "error": "\n\nRuntimeError: Can not perform action when filesystem is not mounted\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.5/concurrent/futures/thread.py\", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/tmp/actions/storage_cluster/d540b6e13b74f39db661811291586903.py\", line 50, in stop\n    cluster = get_cluster(service)\n  File \"/tmp/actions/storage_cluster/d540b6e13b74f39db661811291586903.py\", line 237, in get_cluster\n    return StorageCluster.from_ays(service)\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StorageCluster.py\", line 28, in from_ays\n    storages_server = StorageServer.from_ays(ardb_service)\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StorageCluster.py\", line 143, in from_ays\n    ardb = ARDB.from_ays(ardb_services)\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/ARDB.py\", line 27, in from_ays\n    container = Container.from_ays(service.parent)\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/Container.py\", line 91, in from_ays\n    fs = sp.get(fs_service.name)\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py\", line 232, in get\n    for filesystem in self.list():\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py\", line 221, in list\n    for subvol in self.raw_list():\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py\", line 178, in raw_list\n    mountpoint = self._get_mountpoint()\n  File \"/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py\", line 167, in _get_mountpoint\n    raise RuntimeError(\"Can not perform action when filesystem is not mounted\")\nRuntimeError: Can not perform action when filesystem is not mounted"
}
```

#### Stacktrace in ays logs
```
Error of job: storage_cluster!diegeert (stop):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/d540b6e13b74f39db661811291586903.py", line 50, in stop
    cluster = get_cluster(service)
  File "/tmp/actions/storage_cluster/d540b6e13b74f39db661811291586903.py", line 237, in get_cluster
    return StorageCluster.from_ays(service)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StorageCluster.py", line 28, in from_ays
    storages_server = StorageServer.from_ays(ardb_service)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StorageCluster.py", line 143, in from_ays
    ardb = ARDB.from_ays(ardb_services)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/ARDB.py", line 27, in from_ays
    container = Container.from_ays(service.parent)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/Container.py", line 91, in from_ays
    fs = sp.get(fs_service.name)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 232, in get
    for filesystem in self.list():
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 221, in list
    for subvol in self.raw_list():
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 178, in raw_list
    mountpoint = self._get_mountpoint()
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 167, in _get_mountpoint
    raise RuntimeError("Can not perform action when filesystem is not mounted")
RuntimeError: Can not perform action when filesystem is not mounted
```

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce

**Comment by ahmedelsayed-93** [comment]
cannot reproduce
orchestrator : master : 2bd42f3
0-core : master : 4ee374a
jumpscale : js9
