### ISSUE TITLE
can't post job in container with environment variable 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#297]
## Api 
POST /nodes/{nodeid}/containers/{containername}/jobs

## Issue
![selection_362](https://cloud.githubusercontent.com/assets/24386802/26531226/f22830ee-43e4-11e7-9a3d-de90f5f3d5a8.png)

## SV
885f46c725a48b7882688773ff1c94d716d76c40

**Comment by Dinaamagdy** [comment]
still have the same error : 
![selection_379](https://cloud.githubusercontent.com/assets/24386802/26674809/eabea47a-46c1-11e7-8a3d-8a899f542207.png)

##SV
0c7bbf5601db7fe46338a4465f8b3dca00d176e8

**Comment by zaibon** [comment]
The screenshots seem to show that the orchestrator is not even running when you send the request. Can you confirm ?

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduc 202 , please verify

**Comment by Dinaamagdy** [comment]
#### still can reproduce it , orchestrator is running and give this output after request  : 
```
2017/06/07 05:58:28 http: panic serving 10.147.17.139:53424: assignment to entry in nil map                    [4/1316]
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc42015e320)
        /opt/go/root/src/net/http/server.go:1721 +0xd0
panic(0x87f7e0, 0xc42016f860)
        /opt/go/root/src/runtime/panic.go:489 +0x2cf
github.com/zero-os/0-orchestrator/api/node.NodeAPI.StartContainerJob(0x7fffccfdacbd, 0x13, 0xc42006b080, 0xc42000e1b8, 
0x7f07482d50a0, 0xc4200c3980, 0xc42000be00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_api_StartContainerJob.go:34 +0x1e2
github.com/zero-os/0-orchestrator/api/node.(*NodeAPI).StartContainerJob(0xc42012a280, 0x7f07482d50a0, 0xc4200c3980, 0xc
42000be00)
        <autogenerated>:153 +0x86
github.com/zero-os/0-orchestrator/api/node.(NodesInterface).StartContainerJob-fm(0x7f07482d50a0, 0xc4200c3980, 0xc42000
be00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_if.go:380 +0x50
net/http.HandlerFunc.ServeHTTP(0xc4202437c0, 0x7f07482d50a0, 0xc4200c3980, 0xc42000be00)
        /opt/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420052b40, 0x7f07482d50a0, 0
xc4200c3980, 0xc42000be00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb0eee0, 0xc42000e02
0, 0xb0e260, 0xc420052b40, 0xb13660, 0xc42044c540, 0xc42000bc00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers/handlers.go:75 +0x17d
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420375340, 0xb1
3660, 0xc42044c540, 0xc42000bc00)
        <autogenerated>:11 +0x86
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420353c00, 0xb13660, 0xc42044c540, 0xc
420107100)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:62 +0x117
net/http.serverHandler.ServeHTTP(0xc4202c7970, 0xb13660, 0xc42044c540, 0xc420107100)
        /opt/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42015e320, 0xb13f20, 0xc420019a00)
        /opt/go/root/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /opt/go/root/src/net/http/server.go:2668 +0x2ce
2017/06/07 05:58:28 http: panic serving 10.147.17.139:53458: assignment to entry in nil map
goroutine 102 [running]:
net/http.(*conn).serve.func1(0xc42015e6e0)
        /opt/go/root/src/net/http/server.go:1721 +0xd0
panic(0x87f7e0, 0xc42016fa40)
        /opt/go/root/src/runtime/panic.go:489 +0x2cf
github.com/zero-os/0-orchestrator/api/node.NodeAPI.StartContainerJob(0x7fffccfdacbd, 0x13, 0xc42006b080, 0xc42000e1b8, 
0x7f07482d50a0, 0xc4200c3b40, 0xc420068300)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_api_StartContainerJob.go:34 +0x1e2
github.com/zero-os/0-orchestrator/api/node.(*NodeAPI).StartContainerJob(0xc42012a280, 0x7f07482d50a0, 0xc4200c3b40, 0xc
420068300)
        <autogenerated>:153 +0x86
github.com/zero-os/0-orchestrator/api/node.(NodesInterface).StartContainerJob-fm(0x7f07482d50a0, 0xc4200c3b40, 0xc42006
8300)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_if.go:380 +0x50
net/http.HandlerFunc.ServeHTTP(0xc4202437c0, 0x7f07482d50a0, 0xc4200c3b40, 0xc420068300)
        /opt/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420052b40, 0x7f07482d50a0, 0
xc4200c3b40, 0xc420068300)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb0eee0, 0xc42000e02
0, 0xb0e260, 0xc420052b40, 0xb13660, 0xc42044c620, 0xc420068100)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers/handlers.go:75 +0x17d
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420375340, 0xb1
3660, 0xc42044c620, 0xc420068100)
        <autogenerated>:11 +0x86
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420353c00, 0xb13660, 0xc42044c620, 0xc
42000bf00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:62 +0x117
net/http.serverHandler.ServeHTTP(0xc4202c7970, 0xb13660, 0xc42044c620, 0xc42000bf00)
        /opt/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42015e6e0, 0xb13f20, 0xc420019f40)
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420353c00, 0xb13660, 0xc42044c620, 0xc
42000bf00)
        /opt/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:62 +0x117
net/http.serverHandler.ServeHTTP(0xc4202c7970, 0xb13660, 0xc42044c620, 0xc42000bf00)
        /opt/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42015e6e0, 0xb13f20, 0xc420019f40)
        /opt/go/root/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /opt/go/root/src/net/http/server.go:2668 +0x2ce

```
#### and I can list jobs after this request again 
## Software Version 
5e2a9594e0843cea4cbcbe1355e48f42bf5db0a7

**Comment by Dinaamagdy** [comment]
## SV 
42bd7ade26421f525e665abfeb1d7d19b8143a37
