### ISSUE TITLE
vms_api: error when creating VM

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#298]
### API
POST nodes/{nodeid}/vms

### create vm request 
![image](https://cloud.githubusercontent.com/assets/24386820/26582979/7f6358bc-4543-11e7-9447-863a23edd476.png)

### create storagecluster request
![image](https://cloud.githubusercontent.com/assets/24386820/26583010/a4c40c14-4543-11e7-8ec3-ba8d208261fe.png)

### create vdisk request
![image](https://cloud.githubusercontent.com/assets/24386820/26583022/b265a9cc-4543-11e7-907d-4325c06c295c.png)

### ays error

![image](https://cloud.githubusercontent.com/assets/24386820/26544969/37c90b12-4464-11e7-97fd-940e7e91235a.png)

```
[Mon29 09:40] - Job.py              :64  :j.jobcontroller.job.d50c024b8b1c60c0c46ff26cda35bb2a - INFO     - job job: nbdserver!vm (install)[13/1726]
essfuly
[Mon29 09:40] - Job.py              :64  :j.jobcontroller.job.069a24e0c42577eb38a6ba0a1eadaca5 - INFO     - job job: nbdserver!vm (start) done suces
sfuly
[Mon29 09:40] - Container.py        :121 :j.sal.g8os                     - DEBUG    - get container info
[Mon29 09:40] - ceed3dbddefbaa490b0cfefb3aa1a972.py:73  :j.jobcontroller.job.400512bdd37dd243b3198d702b747f7d - INFO     - create vm vm
2017-05-29 09:40:47 - (network)[INFO][10.147.17.203:60240]: GET http://10.147.17.231:5000/ays/repository/resourcepool/service/vm/vm  200 14841
[Mon29 09:40] - Job.py              :55  :j.jobcontroller.job.400512bdd37dd243b3198d702b747f7d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/ceed3dbddefbaa490b0cfefb3aa1a972.py", line 92, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 1451, in create
    return self._client.sync('kvm.create', args)
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 520, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-05-29T09:41:02.5184
35Z qemu-system-x86_64: -drive file=nbd:unix:/mnt/container-11/server.socket.vm:exportname=ubuntu-vdisk,format=raw,if=none,id=drive-virtio-disk0,iop
s=2000: Failed to connect socket: Connection refused')"
)
[Mon29 09:40] - RunStep.py          :84  :j.atyourservice                - INFO     - runstep 3: error
[Mon29 09:40] - Run.py              :108 :j.atyourservice                - ERROR    - error during execution of step 3 in run 0503185d7ca8f29e4d8692
1c80e2db8e
Error of job: vm!vm (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/ceed3dbddefbaa490b0cfefb3aa1a972.py", line 92, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 1451, in create
    return self._client.sync('kvm.create', args)
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 520, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-05-29T09:41:02.5184
35Z qemu-system-x86_64: -drive file=nbd:unix:/mnt/container-11/server.socket.vm:exportname=ubuntu-vdisk,format=raw,if=none,id=drive-virtio-disk0,iop
s=2000: Failed to connect socket: Connection refused')"
)
```

**Comment by grimpy** [comment]
@ahmedelsayed-93 any hints for reproducing?

**Comment by ahmedelsayed-93** [comment]
@grimpy 
i just created storagecluster,  vdisk and vm  on a clean environment

**Comment by Dinaamagdy** [comment]
## still have error in ays : 
```
Error of job: vm!vm (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/4720000f6ee37801510480baf2b532b5.py", line 61, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1613, in create
    return self._client.sync('kvm.create', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 533, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to 
monitor: 2017-06-05T15:27:29.149964Z qemu-system-x86_64: -drive file=nbd:unix:/mnt/container-6/server.socket.vm:exp
ortname=ubuntu-test-vdisk,format=raw,if=none,id=drive-virtio-disk0,iops=2000: Failed to connect socket: Connection 
refused')"
)
```

**Comment by grimpy** [comment]
Relates to https://github.com/zero-os/0-Disk/issues/243

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by grimpy** [comment]
Relates to https://github.com/zero-os/0-Disk/issues/243

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by grimpy** [comment]
Should be fixed when using configuration blueprint
```
configuration__myconfig:
  configurations:
  - key: 0-disk-flist
    value: https://hub.gig.tech/gig-official-apps/0-disk-1.1.0-alpha-3.flist
```

**Comment by ahmedelsayed-93** [comment]
### software versions
orchestrator : bb0fb08

**Comment by ahmedelsayed-93** [comment]
### Scenario
- create vm 
- make sure it is running 
![image](https://user-images.githubusercontent.com/24386820/26870282-c7078058-4b6f-11e7-97e9-4c49fac54fc4.png)

- shutdown the vm
- start the vm 



### result
```
[Wed07 08:50] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 5: error
[Wed07 08:50] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 5 in run 789bd2e1b8eb8e0540293a366f160bd7
Error of job: vm!vm (start):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/d094ba9bdac9d9fed70458dfe00f58ac.py", line 348, in start
    j.tools.async.wrappers.sync(service.executeAction('install'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 676, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 701, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/d094ba9bdac9d9fed70458dfe00f58ac.py", line 97, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1613, in create
    return self._client.sync('kvm.create', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 533, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-06-07T08:50:51.635408Z qemu-system-x86_64: -drive file=nbd:unix:/mnt/container-13/server.socket.vm:expo
rtname=ubuntu,format=raw,if=none,id=drive-virtio-disk0,iops=2000: Failed to connect socket: Connection refused')"
)


```

**Comment by grimpy** [comment]
@ahmedelsayed-93 please confirm you've used the above configuration service?

**Comment by Dinaamagdy** [comment]
it work by create configuration blueprint manually with correct 0-disk flist and run it .
## Software Version 
branch: 1.1.0-alpha-3
commit : 8759de72b1b9e7326497a9238f52c677dad6f7ac
