### ISSUE TITLE
Create Vdisk with any storagecluster name doesn't fail 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#300]
## Steps : 
-Create vdisk with doesn't exist storagecluster.

## issue 
Vdisk created in response as shown: 
![selection_369](https://cloud.githubusercontent.com/assets/24386802/26553648/eef60e20-448c-11e7-88d5-bec0436a36fd.png)

### but ays give this error : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/10cb6a1cc04b9e9b2810d131be28fce5.py", line 93, in install
    targetconfig = get_storagecluster_config(service)
  File "/tmp/actions/vdisk/10cb6a1cc04b9e9b2810d131be28fce5.py", line 64, in get_storagecluster_config
    instance=storagecluster)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 376, in serviceGet
    (role, instance), level=1, source="", tags="", msgpub="")
JSExceptions.NotFound: ERROR: Cannot find service storage_cluster:fake_cluster ((type:notfound)
```

**Comment by Dinaamagdy** [comment]
## SV
0c7bbf5601db7fe46338a4465f8b3dca00d176e8
