### ISSUE TITLE
storageclusters_apis: error when create storagecluster 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#329]
### API
```POST /storageclusters```

### storagecluster status
status : empty
```json
curl -X GET http://192.168.191.85:8080/storageclusters/mycluster
{
	"dataStorage": [
		{
			"container": "cluster_0cc47a740636_mycluster_sdb_data_0",
			"id": 0,
			"ip": "192.168.191.127",
			"port": 2000,
			"status": "ready"
		},
		{
			"container": "cluster_0cc47a740610_mycluster_sdb_data_1",
			"id": 1,
			"ip": "192.168.191.112",
			"port": 2001,
			"status": "ready"
		},
		{
			"container": "cluster_0cc47a740646_mycluster_sdb_data_2",
			"id": 2,
			"ip": "192.168.191.248",
			"port": 2002,
			"status": "ready"
		},
		{
			"container": "cluster_0cc47a740632_mycluster_sdc_data_3",
			"id": 3,
			"ip": "192.168.191.33",
			"port": 2003,
			"status": "ready"
		}
	],
	"driveType": "hdd",
	"label": "mycluster",
	"metadataStorage": [
		{
			"container": "cluster_0cc47a740632_mycluster_sdc_metadata_4",
			"id": 4,
			"ip": "192.168.191.33",
			"port": 2004,
			"status": "ready"
		}
	],
	"nodes": [
		"0cc47a740632",
		"0cc47a740610",
		"0cc47a740646",
		"0cc47a740636"
	],
	"status": "empty"
}
```
### ays error
```
Thu01 09:43] - Job.py              :55  :j.jobcontroller.job.f48ebc96a69ed8c1b7da66e87540992d - ERROR    - Traceback (most recent c
all last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/57c5cdfb8beaef7d6ca94a6870279a9e.py", line 4, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 670, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 695, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/57c5cdfb8beaef7d6ca94a6870279a9e.py", line 133, in start
    raise j.exceptions.RuntimeError("container didn't started")
JSExceptions.RuntimeError: ERROR: container didn't started ((type:runtime.error)
[Thu01 09:43] - RunStep.py          :84  :j.atyourservice                - INFO     - runstep 3: error
[Thu01 09:43] - Run.py              :108 :j.atyourservice                - ERROR    - error during execution of step 3 in run 72667d
fd4a47deffa66cfa0c607e3629
Error of job: container!cluster_0cc47a740632_mycluster_sdc_metadata_4 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/c2f50bedc9e4e6cdb65e35ee50376a37.py", line 4, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 670, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 695, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/c2f50bedc9e4e6cdb65e35ee50376a37.py", line 133, in start
    raise j.exceptions.RuntimeError("container didn't started")
JSExceptions.RuntimeError: ERROR: container didn't started ((type:runtime.error)
```

### SV
js : 8fd47635
0-orchestrator 0c7bbf5

**Comment by serboctor** [comment]
Ahmed says it is not reproducable on js9.

**Comment by Dinaamagdy** [comment]
## Software version 
af5cc20dffa47b6cbd695a8c680c9ca856e3fc90
