### ISSUE TITLE
Vdisk doesn't deleted after delete it's storagecluster

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#348]
## Steps:
- Create storage cluster.
- Create Vdisk with it .
- delete this storage cluster 

## Expected result 
- vdisk be deleted 
## Issue
Vdisk exist  and be halted then If you try to delete it , you will have this error 

![image](https://cloud.githubusercontent.com/assets/24386802/26761111/d4418d74-4929-11e7-8fff-1bdb984651fd.png)

```
ays error 
 - schedule action delete on service:vdisk!ubuntu-test-vdisk5
init done
blueprint done
2017-06-04 11:21:06 - (network)[INFO][127.0.0.1:42954]: POST http://127.0.0.1:5000/ays/repository/resourcepool-server/blueprint/vdisk_ubuntu-test-vdisk5_delete_1496575265  200 71
2017-06-04 11:21:06 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 365, in serviceGet
    return self.db.services.services[key]
KeyError: 'fde431de614f960494c21dcf51c6e0e4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_if.py", line 68, in post
    return await auth(request, ays_api.createRun(request, repository))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_if.py", line 16, in auth
    return await func
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_api.py", line 257, in createRun
    to_execute = repo.findScheduledActions()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 627, in findScheduledActions
    if is_producer_in_error(service, action):
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 606, in is_producer_in_error
    for producers in service.producers.values():
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 391, in producers
    producers[role].append(self.aysrepo.serviceGet(key=prod.key))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 367, in serviceGet
    raise j.exceptions.NotFound('cant find service with key %s' % key)
JSExceptions.NotFound: ERROR: cant find service with key fde431de614f960494c21dcf51c6e0e4 ((type:notfound)

2017-06-04 11:21:06 - (network)[INFO][127.0.0.1:42956]: POST http://127.0.0.1:5000/ays/repository/resourcepool-server/aysrun  500 144
2017-06-04 11:21:06 - (network)[INFO][127.0.0.1:42956]: PUT http://127.0.0.1:5000/ays/repository/resourcepool-server/blueprint/vdisk_ubuntu-test-vdisk5_delete_1496575265/archive  200 71
```

**Comment by zaibon** [comment]
I think we should instead not allow to delete a storage cluster when there are vdisk in it.

**Comment by khaledkbadr** [comment]
Should be done after implementation of this FR
https://github.com/Jumpscale/ays9/issues/16

**Comment by Dinaamagdy** [comment]
## Software Version 
8cb8259f8d8b36008469d565d5ffe333e4c5be84
