### ISSUE TITLE
Installation script doesn't install the zerotier client

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#352]
After install AYS and run the blueprint I found this log 

```bash
2017-06-04 13:38:42 - (network)[INFO][127.0.0.1:37822]: POST http://localhost:5000/ays/repository/orchestrator-server/blueprint/bootstrap.bp  200 41               │·······················
[Sun04 13:38] - Job.py              :56  :j.core.jobcontroller.job.c34f3b2c1ff31ef7c8e52c56c2c8c4d6 - ERROR    - Traceback (most recent call last):                │·······················
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run                                                                                          │·······················
    result = self.fn(*self.args, **self.kwargs)                                                                                                                    │·······················
  File "/tmp/actions/bootstrap.g8os/87723ee841990fc4a47dd2a0526aae4a.py", line 144, in bootstrap                                                                   │·······················
    from zerotier import client                                                                                                                                    │·······················
ImportError: No module named 'zerotier'
```

**Reproduce steps**
Install an environment using the installation script and run the discovering blueprint
https://github.com/zero-os/0-orchestrator/blob/master/scripts/installgrid.sh

**Comment by Dinaamagdy** [comment]
## Sv
f74e7be69b8594dba2a6b4d7c15933f25c3919b0
