### ISSUE TITLE
GW Can't have a nw interface with default or zerotier type

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#384]
GW Can't have a nw interface with default or zerotier type. It will generate an error in the AYS cause it's trying to get a gateway however the default type doesn't have config parameter.

**Payload**
```json
{
  "name":"GW_14",
  "domain":"xTremX",
  "nics":[
    {
      "name":"private",
      "type":"default",
			"id": "0"
    },	
	{
		"name":"public",
		"type":"vlan",
		"id":"10",
		"config":{
			"cidr":"192.168.2.0/24",
			"gateway": "192.168.2.1"
      }
    }
	]
}
```

**AYS ERROR**
```bash

[Tue06 09:47] - Job.py              :56  :j.core.jobcontroller.job.01d2097dbcefc67c0cf1fbfbe2b6a99d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/e09b830d859d9a7c23522b734f48d9ab.py", line 134, in input
    raise j.exceptions.Input("Gateway should have at least one Private Address (no gw defined)")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: Gateway should have at least one Private Address (no gw defined) ((type:input.error)
[Tue06 09:47] - ays_api.py          :429 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 ERROR: Gateway should have at least one Private Address (no gw defined) ((type:input.error)
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 426, in executeBlueprint
    await repo.blueprintExecute(path=bp.path)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 520, in blueprintExecute
    await bp.load(role=role, instance=instance)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 481, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 32, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 25, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 112, in _initFromActor
    args2 = await self.input(args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 613, in input
    args = await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/e09b830d859d9a7c23522b734f48d9ab.py", line 134, in input
    raise j.exceptions.Input("Gateway should have at least one Private Address (no gw defined)")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: Gateway should have at least one Private Address (no gw defined) ((type:input.error)
```

**Version**
master

**Comment by FastGeert** [comment]
There are no restrictions of possible configuration combinations we should hardcode in AYS. Please remove the business rules on this.

**Comment by Dinaamagdy** [comment]
## Ays give this error when create with this parameters
![selection_395](https://user-images.githubusercontent.com/24386802/26837084-cdbd3160-4adc-11e7-8ab8-e84667d2c8c8.png)

```
Error of job: gateway!GW_20 (install):                                                                        [19/1885]
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/8bde97cc86f69dbb6310df8c0fccacc0.py", line 169, in install
    j.tools.async.wrappers.sync(service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 674, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 699, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/8bde97cc86f69dbb6310df8c0fccacc0.py", line 142, in start
    j.tools.async.wrappers.sync(firewall.executeAction('install'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 674, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 699, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/firewall/e9f5e75d5d51e22e6b777ae9d6ec617b.py", line 86, in install
    apply_rules(job, gwdata)
  File "/tmp/actions/firewall/e9f5e75d5d51e22e6b777ae9d6ec617b.py", line 136, in apply_rules
    firewall.apply_rules()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/gateway/firewall.py", line 32, in apply_rules
    raise RuntimeError("Failed to apply nftables {} {}".format(job.stdout, job.stderr))
RuntimeError: Failed to apply nftables  /etc/nftables.conf:9:22-22: Error: syntax error, unexpected '}'
define priv_iface={  }
                     ^
/etc/nftables.conf:49:22-31: Error: unknown identifier 'priv_iface'
                iif $priv_iface jump private
                     ^^^^^^^^^^
/etc/nftables.conf:57:22-31: Error: unknown identifier 'priv_iface'
                iif $priv_iface oif $priv_iface accept
                     ^^^^^^^^^^
/etc/nftables.conf:61:22-31: Error: unknown identifier 'priv_iface'
                oif $priv_iface ct status dnat accept
                     ^^^^^^^^^^
```
## Software Version
04aa341048d0e3048131c5d205d6eeb6d68dbacd

**Comment by FastGeert** [comment]
@Dinaamagdy id on a default network does not make sense

**Comment by grimpy** [comment]
Changed firewall rules to only kick in when private and network interfaces are found

**Comment by Dinaamagdy** [comment]
## Software Version 
5e2a9594e0843cea4cbcbe1355e48f42bf5db0a7
