### ISSUE TITLE
vdisks_api: delete vdisk returns internal server error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#387]
### request and response 

![image](https://cloud.githubusercontent.com/assets/24386820/26824768/f6b6b76e-4ab2-11e7-9a42-d9eb1ee306e1.png)

### ays log
```
[Tue06 10:16] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 3: error
[Tue06 10:16] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 3 in run 2b3055b5b1e78005da1367444e15c173
Error of job: vdisk!a35d6174b (delete):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/28cebe06ea8cdec2f5f37241a062a1d1.py", line 131, in delete
    container = create_from_template_container(service, node)
  File "/tmp/actions/vdisk/28cebe06ea8cdec2f5f37241a062a1d1.py", line 169, in create_from_template_container
    config = get_configuration(job.service.aysrepo)
NameError: name 'job' is not defined
```
### software versions
orchestrator : af5cc20dff

**Comment by ahmedelsayed-93** [comment]
### software versions
orchestrator- : 93bf2ce2
