### ISSUE TITLE
AYS should prevent creating a gw with two nics with the same name

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#416]
The following payload will ask AYS to create a gateway with two nics with the same name, AYS will create the GW and return 201 after that AYS will throw an error.

```json
{
  "name":"gw_22",
  "domain":"tester",
  "nics":[
    {
      "name":"public",
      "type":"vlan",
      "id":"0",
      "config":{
        "cidr":"172.18.0.10/24",
        "gateway":"172.18.0.1"
      }
    },
    {
      "name":"private",
      "type":"vxlan",
      "id":"100",
      "config":{
        "cidr":"192.168.112.22/24"
      },
      "dhcpserver":{
        "nameservers":[
          "8.8.8.8"
        ],
        "hosts":[
          {
            "macaddress":"00:A0:C9:14:C8:29",
            "hostname":"sarah",
            "ipaddress":"192.168.112.11"
          }
        ]
      }
    },
		
		 {
      "name":"private",
      "type":"vxlan",
      "id":"110",
      "config":{
        "cidr":"192.168.112.22/24"
      },
      "dhcpserver":{
        "nameservers":[
          "8.8.8.8"
        ],
        "hosts":[
          {
            "macaddress":"00:A0:C9:14:C8:29",
            "hostname":"sarah",
            "ipaddress":"192.168.112.11"
          }
        ]
      }
    }
  ]
}
```

**AYS log**
```bash
init done
blueprint done
2017-06-07 09:48:55 - (network)[INFO][127.0.0.1:55850]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/gateway_gw_22_install_1496828927  200 61
INFO:network:
[Wed07 09:48] - Job.py              :66  :j.core.jobcontroller.job.810741810020ad4cfa9b3d07a1719749 - INFO     - job job: container!gw_22 (monitor) done sucessfuly
2017-06-07 09:48:55 - (network)[INFO][127.0.0.1:55854]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/aysrun  200 531
INFO:network:
[Wed07 09:48] - RunStep.py          :69  :j.atyourservice.server         - INFO     - execute job: container!gw_22 (install)
2017-06-07 09:48:57 - (network)[INFO][127.0.0.1:55854]: PUT http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/gateway_gw_22_install_1496828927/archive  200 61
INFO:network:
[Wed07 09:48] - Job.py              :56  :j.core.jobcontroller.job.02e229571df3356ce6618f00b9ebd0c6 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 133, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 168, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "name 'private' is passed twice in the container"
[Wed07 09:48] - Job.py              :56  :j.core.jobcontroller.job.1c29a906ed8af2f3d67babad94909f7b - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 116, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 674, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 699, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 133, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 168, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "name 'private' is passed twice in the container"
[Wed07 09:48] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Wed07 09:48] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e903edf8215e9a62b5418041f36f6baf
Error of job: container!gw_22 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 116, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 674, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 699, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 133, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 168, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "name 'private' is passed twice in the container"
[Wed07 09:49] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Wed07 09:49] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e903edf8215e9a62b5418041f36f6baf
Error of job: container!gw_22 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 116, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 674, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 699, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/ab96dd5ea8390c4b68aa42c6681f424a.py", line 133, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 168, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "name 'private' is passed twice in the container"
```

**List containers**
```json
	{
		"flist": "https://hub.gig.tech/gig-official-apps/g8osgw.flist",
		"hostname": "",
		"name": "gw_22",
		"status": "halted"
	}
```

**Comment by muhamadazmy** [comment]
`throw an error` not `through an error`

**Comment by FastGeert** [comment]
Add input validation in gw service

**Comment by ahmedelsayed-93** [comment]
### software version
orchestrator : master : db68214
