### ISSUE TITLE
Implement vdisk rollback for db and bootdisk

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#430]

**Comment by khaledkbadr** [comment]
blocked on https://github.com/zero-os/0-Disk/issues/237

**Comment by ahmedelsayed-93** [comment]
error when creating vm with vdisk which has storage cluster and tlog cluster  
```
[Mon19 15:20] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 2: error                   │···········································
[Mon19 15:20] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 2 in│···········································
 run cc512292afc24d69ab41ffc0c9717aed                                                                                    │···········································
Error of job: tlogserver!vm4 (install):                                                                                  │···········································
*TRACEBACK*********************************************************************************                              │···········································
Traceback (most recent call last):                                                                                       │···········································
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run                                                │···········································
    result = self.fn(*self.args, **self.kwargs)                                                                          │···········································
  File "/tmp/actions/tlogserver/8266fb56f6911e6c6c2132f23caf3989.py", line 73, in install                                │···········································
    container.node.client.nft.open_port(port)                                                                            │···········································
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1927, in open_port                   │···········································
    return self._client.json('nft.open_port', args)                                                                      │···········································
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 543, in json                         │···········································
    result = self.sync(command, arguments)                                                                               │···········································
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 533, in sync                         │···········································
    raise RuntimeError('invalid response: %s' % result.state, result)                                                    │···········································
RuntimeError: ('invalid response: ERROR', STATE: ERROR                                                                   │···········································
STDOUT:                                                                                                                  │···········································
                                                                                                                         │···········································
STDERR:                                                                                                                  │···········································
                                                                                                                         │···········································
DATA:                                                                                                                    │···········································
"rule exists"                                                                                                            │···········································
)                                                                                                                        │···········································
  
```

### software version
orchestrator : master : 7d9e1c555

**Comment by ahmedelsayed-93** [comment]
blocked on https://github.com/zero-os/0-orchestrator/issues/429

**Comment by ahmedelsayed-93** [comment]
```ERROR: tlogserver didn't stopped``` when stop the vm 
```
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: tlogserver didn't stopped ((type:runtime.error)
[Tue20 15:39] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Tue20 15:39] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e0f951348425522d836846c5022a4eac
Error of job: vm!ooo (stop):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/92da9f79f93e7949ab565715c2d1258b.py", line 9, in stop
    cleanupzerodisk(job)
  File "/tmp/actions/vm/92da9f79f93e7949ab565715c2d1258b.py", line 114, in cleanupzerodisk
    j.tools.async.wrappers.sync(tlogserver.executeAction('stop'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/tlogserver/c7e4e637560f6a0fa728be97e21e1167.py", line 20, in stop
    raise j.exceptions.RuntimeError("tlogserver didn't stopped")
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: tlogserver didn't stopped ((type:runtime.error)
```

**Comment by grimpy** [comment]
I'm pushing this to next release to test this with newer version of 0-disk.
From the looks of it the code of 0-ochestrator looks ok

**Comment by khaledkbadr** [comment]
Looks like the implementation on the orchestrator end is complete. This issue is blocked on https://github.com/zero-os/0-Disk/issues/288 and https://github.com/zero-os/0-Disk/issues/323 though

**Comment by khaledkbadr** [comment]
SIGTERM handler was added to nbdserver which we believe will solve the problem. But other changes added to 0-Disk breaks the current implementation. So I need to do the following to make everything works with new 0-Disk implementation:
* Migrate templates' keys in hub.gig.com 
* Adjust config of the nbdserver to new format

**Comment by Dinaamagdy** [comment]
can't start Vm again after stop it 
```
[Wed26 16:49] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 2 in run 4cd5c68e9428ffd72c4d1c796e3f282d
Error of job: vm!vm2525 (start):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/39b597bca2a68d22cb54429c94d52688.py", line 128, in start
    j.tools.async.wrappers.sync(service.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 683, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 708, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/39b597bca2a68d22cb54429c94d52688.py", line 299, in install
    medias = _start_nbd(job)
  File "/tmp/actions/vm/39b597bca2a68d22cb54429c94d52688.py", line 352, in _start_nbd
    raise j.exceptions.RuntimeError("Failed to start nbds, no nbds created to start")
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to start nbds, no nbds created to start ((type:runtime.error)
```

**Comment by Dinaamagdy** [comment]
## Software Version 
967b777e18d52e8ce56737d5ac7ddf5682c65778
