### ISSUE TITLE
AYS should prevent creating a gw with not existing bridge

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#446]
The following payload will ask AYS to create a gateway with not existing bridge.  AYS will create the GW and return 201 after that AYS will throw an error.

```json
{	
  "name": "gw_4",
  "domain": "test",
  "nics": [
    {
      "name": "public",
      "type": "bridge",
      "id": "bridge_1",
      "config": {
        "cidr": "192.168.100.2/24",
        "gateway": "192.168.100.1"
      }
    },
    {
      "name": "private",
      "type": "vxlan",
      "id": "1",
      "config": {
        "cidr": "192.168.112.1/24"
      },
      "dhcpserver": {
        "nameservers": [
          "8.8.8.8"
        ],
        "hosts": [
          {
            "macaddress": "00:A0:C9:14:C8:00",
            "hostname": "container1",
            "ipaddress": "192.168.112.10"
          },
          {
            "macaddress": "00:A0:C9:14:C8:01",
            "hostname": "container2",
            "ipaddress": "192.168.112.11"
          }
        ]
      }
    }
  ],
  "httpproxies": [
    {
      "host": "container1",
      "destinations": [
        "http://192.168.112.10:5000"
      ],
      "types": [
        "http"
      ]
    },
    {
      "host": "container2",
      "destinations": [
        "http://192.168.112.11:5000"
      ],
      "types": [
        "http"
      ]
    }
  ],
  
  "portforwards":[
    {
      "srcport":80,
      "srcip":"192.168.100.2",
      "dstport":8080,
      "dstip":"192.168.112.10",
      "protocols":[
        "tcp"
      ]
    }
  ]
  
}
```
**AYS Error**
```bash
    self._create_container()                                                                                                                               [49/1878]
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "bridge 'bridge_1' not found: Link not found"
[Sun11 13:34] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Sun11 13:34] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e54d985df16c4050832401d7f7813e73
Error of job: container!gw_3 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/729d15f0544523d53516803a2bb5036c.py", line 182, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 698, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/729d15f0544523d53516803a2bb5036c.py", line 101, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 168, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 161, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "bridge 'bridge_1' not found: Link not found"


*****************************************************************************************
```

**Comment by FastGeert** [comment]
Need to add validation in the input of the gw service

**Comment by ahmedelsayed-93** [comment]
### software version
orchestrator : master : db68214f
