### ISSUE TITLE
GW crashes when zerotierbridge is defined without a cidr

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-orchestrator#450]
Create a gateway where one of the nics has a zerotierbridge but doesn't have a cidr.
The following crash occurs in ays:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/632d6f1466167f549f5c935444249cf3.py", line 130, in install
    j.tools.async.wrappers.sync(service.executeAction('start'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in executeAction
    return await self.executeActionJob(action, args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 698, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/632d6f1466167f549f5c935444249cf3.py", line 241, in start
    ip.addr.delete(nicname, nic['config']['cidr'])
KeyError: 'config'
```

**Comment by FastGeert** [comment]
Does it needs a cidr, or should the code be more robust

**Comment by grimpy** [comment]
It doesnt require it, it could be you are bridging something that gets its ip from dhcp, we could read the ip from the interface instead

**Comment by Dinaamagdy** [comment]
can't verify due to 
https://github.com/zero-os/0-orchestrator/issues/487

**Comment by Dinaamagdy** [comment]
## Software Version 
d627d44ef4a6e9c49e6b9c6d30f571773a366fe5
