### ISSUE TITLE
install-orchestrator.sh fails on line 112: unexpected error

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-orchestrator#462]
After having removed both my existing Docker container and images, here are the exact commands that I executed:
`export GIGDIR="/home/user/$USER/gig9"`
`rm -rf $GIGDIR`
`export GIGBRANCH="9.0.0"`
`export GIGSAFE=1`
`curl https://raw.githubusercontent.com/Jumpscale/developer/${GIGBRANCH}/jsinit.sh?$RANDOM > /tmp/jsinit.sh`
`bash /tmp/jsinit.sh`
`source ~/.jsenv.sh`
`js9_build -l -p`
`ssh -A root@localhost -p 2222`
`cd /tmp`
`export BRANCH="1.1.0-alpha-3"`
`export ZEROTIERNWID="17d709436c7e8f71`
`export ZEROTIERTOKEN="pahG1Fpq7VHtNpWVv8tt4ScD55nCgVzg"`
`curl -o install-orchestrator.sh https://raw.githubusercontent.com/zero-os/0-orchestrator/${BRANCH}/scripts/install-orchestrator.sh`
`bash install-orchestrator.sh $BRANCH $ZEROTIERNWID $ZEROTIERTOKEN`

Checking `/tmp/install.log`:
```
(js9) root@js9:/tmp# cat /tmp/install.log
200 join OK
zerotier-one: fatal error: cannot bind to local control interface port
Collecting git+https://github.com/zero-os/0-core.git@1.1.0-alpha-3#subdirectory=client/py-client
  Cloning https://github.com/zero-os/0-core.git (to 1.1.0-alpha-3) to ./pip-_cg5__tl-build
Requirement already up-to-date: redis>=2.10.5 in /usr/local/lib/python3.5/dist-packages (from 0-core-client==1.1.0a3)
Installing collected packages: 0-core-client
  Found existing installation: 0-core-client 1.1.0a3
    Uninstalling 0-core-client-1.1.0a3:
      Successfully uninstalled 0-core-client-1.1.0a3
  Running setup.py install for 0-core-client: started
    Running setup.py install for 0-core-client: finished with status 'done'
Successfully installed 0-core-client-1.1.0a3
Collecting git+https://github.com/zero-os/0-orchestrator.git@1.1.0-alpha-3#subdirectory=pyclient
  Cloning https://github.com/zero-os/0-orchestrator.git (to 1.1.0-alpha-3) to ./pip-ome45vma-build
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.5/dist-packages (from 0-orchestrator==1.1.0a3)
Requirement already up-to-date: Jinja2 in /usr/local/lib/python3.5/dist-packages (from 0-orchestrator==1.1.0a3)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil->0-orchestrator==1.1.0a3)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python3.5/dist-packages (from Jinja2->0-orchestrator==1.1.0a3)
Installing collected packages: 0-orchestrator
  Found existing installation: 0-orchestrator 1.1.0a3
    Uninstalling 0-orchestrator-1.1.0a3:
      Successfully uninstalled 0-orchestrator-1.1.0a3
  Running setup.py install for 0-orchestrator: started
    Running setup.py install for 0-orchestrator: finished with status 'done'
Successfully installed 0-orchestrator-1.1.0a3
Requirement already up-to-date: zerotier in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: python-dateutil>=2.6.0 in /usr/local/lib/python3.5/dist-packages (from zerotier)
Requirement already up-to-date: requests>=2.13.0 in /usr/local/lib/python3.5/dist-packages (from zerotier)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil>=2.6.0->zerotier)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.13.0->zerotier)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.13.0->zerotier)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests>=2.13.0->zerotier)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.13.0->zerotier)
[Wed14 14:46] - PrefabCore.py       :1234:j.prefab.core                  - DEBUG    - PROFILECMD:source /root/.jsenv.sh; go version
[Wed14 14:46] - PrefabBase.py       :131 :j.prefabgolang                 - DEBUG    - donecheck:install:True
Already on '1.1.0-alpha-3'
Your branch is up-to-date with 'origin/1.1.0-alpha-3'.
Already on '1.1.0-alpha-3'
Your branch is up-to-date with 'origin/1.1.0-alpha-3'.
File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc56ac636d8>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /ays/repository (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc56ac636d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ays", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 745, in <module>
    cli()
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 84, in create
    print("Error during creation of the repository: {}".format(_extract_error(e)))
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 29, in _extract_error
    raise resp
  File "/opt/code/github/jumpscale/ays9/cmds/ays", line 81, in create
    resp = ayscl.api.ays.createRepository(data=data)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/clients/sync_client/ays_service.py", line 277, in createRepository
    return self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/clients/sync_client/client.py", line 67, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/clients/sync_client/client.py", line 60, in _handle_data
    res = method(uri, data=data, headers=headers, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 560, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /ays/repository (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc56ac636d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /ays/repository (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc56ac636d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I verified that AYS was running, and I could create a repository manually...
(that what fails on line 112: ays repo create -n orchestrator-server -g js9)

**Comment by zaibon** [comment]
We need to add a check in the install script that make sure AYS is started before continuing

**Comment by maxux** [comment]
I'm looging into that asap

**Comment by ahmedelsayed-93** [comment]
### software version
orchestrator : master : ac85844
