### ISSUE TITLE
Update install script to add caddy as a proxy for API

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#469]

**Comment by Dinaamagdy** [comment]
need to implement https

**Comment by ahmedelsayed-93** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/js9", line 19, in <module>
    exec(toexec)
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/apps/PrefabCaddy.py", line 148, in start
    tcpport = int(self.getTCPPort(configpath=configpath))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/apps/PrefabCaddy.py", line 134, in getTCPPort
    raise RuntimeError("Can not find tcpport arg in config file, needs to be '#tcpport:'")
RuntimeError: Can not find tcpport arg in config file, needs to be '#tcpport:'
Can not find tcpport arg in config file, needs to be '#tcpport:'
```

**Comment by mie00** [comment]
Fixed in https://github.com/zero-os/0-orchestrator/pull/521

**Comment by ahmedelsayed-93** [comment]
### software version
orchestrator : master : 6fbcae9
