### ISSUE TITLE
Can't create container with nic 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#487]
## Steps 
- create container with nic any type 
## Issue 
{
    "error": "error executing blueprint for container test creation"
}

```
[Mon19 09:27] - Job.py              :57  :j.core.jobcontroller.job.14a86031cca22ecbc2e0e60cc3557f8d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/0fe41c40b610171e441e3761145d6c48.py", line 201, in input
    if nic['type'] == 'bridge':
KeyError: 'type'
[Mon19 09:27] - ays_api.py          :435 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 'type'
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 426, in executeBlueprint
    await repo.blueprintExecute(path=bp.path, context={'token': extract_token(request)})
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 520, in blueprintExecute
    await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 486, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 32, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 25, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 112, in _initFromActor
    args2 = await self.input(args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 618, in input
    args = await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/0fe41c40b610171e441e3761145d6c48.py", line 201, in input
    if nic['type'] == 'bridge':
KeyError: 'type'
2017-06-19 09:27:31 - (network)[INFO][127.0.0.1:36796]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/container_test_install_1497864450  500 18
INFO:network:
2017-06-19 09:27:31 - (network)[INFO][127.0.0.1:36806]: PUT http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/container_test_install_1497864450/archive  200 62
INFO:network:
```
## Software Version 
db68214fbfb049dd8058402cdc1c93ddd8133584

**Comment by islamTaha12** [comment]
This payload produced the same error with me
```json
{
	"name": "myContainer_1214",
	"hostname": "hostname",
	"nics": [
		{"type": "vxlan",
		 "id": "100",
		"hwaddr":"00:A0:C9:14:C8:30",
		"config":{"dhcp":true}
		}
	],
	"flist": "https://hub.gig.tech/deboeckj/flist-lede-17.01.0-r3205-59508e3-x86-64-generic-rootfs.flist",
	"filesystems": [],
	"hostNetworking": false
}
```

**Comment by Dinaamagdy** [comment]
## Software Version 
d627d44ef4a6e9c49e6b9c6d30f571773a366fe5
