### ISSUE TITLE
Self-healing : NBD server failure

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#489]
Specs : https://github.com/zero-os/0-orchestrator/blob/master/specs/selfhealing/storage.md

**Comment by Dinaamagdy** [comment]
- after  killing  nbd server process, Ays still has no failure in nbd server 
## Software Version
967b777e18d52e8ce56737d5ac7ddf5682c65778

**Comment by ahmedelsayed-93** [comment]
issue still exists
### software version
master : 2043f538

**Comment by Dinaamagdy** [comment]
blocked due to https://github.com/zero-os/0-orchestrator/issues/666

**Comment by Dinaamagdy** [comment]
it doesn't work after migration 
## Steps
- create vm in node1
- migrate vm to node2
- kill nbdeserver for this vm in node2
## Error
```
traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/ed1ccdc6bb5a843ef31d39df3c950018.py", line 195, in watchdog_handler
    vm_service = service.aysrepo.serviceGet(role='vm', instance=service.name)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 349, in serviceGet
    (role, instance), level=1, source="", tags="", msgpub="")
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: Cannot find service vm:vdisks_vm2_248a07e3cc20 ((type:notfound)
[Mon07 08:52] - Job.py              :56  :j.core.jobcontroller.job.b0cd3dd4b8302ebe533c8ff55dba58cc - ERROR    - Traceback (most recent call last):
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112704)
  File "/tmp/actions/node.zero-os/aac16753b7bb0b6f5c7f9f7004b95aef.py", line 233, in streaming
    await cl.global_stream(queue)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 97, in global_stream
    await self.callback(job_id, meta >> 16, line, meta & 0xff)
  File "/tmp/actions/node.zero-os/aac16753b7bb0b6f5c7f9f7004b95aef.py", line 215, in callback
    await srv.executeAction(handler, context=job.context, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 707, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 732, in executeActionJob
    result = await job.execute()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/ed1ccdc6bb5a843ef31d39df3c950018.py", line 195, in watchdog_handler
    vm_service = service.aysrepo.serviceGet(role='vm', instance=service.name)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 349, in serviceGet
    (role, instance), level=1, source="", tags="", msgpub="")
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: Cannot find service vm:vdisks_vm2_248a07e3cc20 ((type:notfound)
```
## Software Version 
012719ca7375c9a5ba500bc403a61a15b0873b53

**Comment by Dinaamagdy** [comment]
can't validate https://github.com/zero-os/0-orchestrator/issues/791

**Comment by Dinaamagdy** [comment]
it doesn't work now as when u kill nbdserver process , ays doesn't recognize that so it doesn't restart again , may this error is one of reason of that 
https://github.com/Jumpscale/ays9/issues/164

## Software Version 
3cb419bdbfc44dbc8cb9a43f67747738d9973821

**Comment by Dinaamagdy** [comment]
## Software Version 
4608799aa49ff1f81154ef0f11a414df67e58797
