### ISSUE TITLE
Import / Export virtual machines

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#556]
Goal  is to be able to export a VM from a certain location and import it in a new one.

Requirements:
- export :
  - VM has to be stopped before it can be exported
  - Export is done using [restic](https://github.com/restic/restic)
  - client need to specify a backend where to store the exported VM
    - proposition for this is to provide a REST server that support restic as a service for the client so it's easy for them to setup a storate server for their exported VM. Restic has a plugin for caddy that we could integrate with our IYO plugin to have a complete product without the need for us to implement a lot. see https://github.com/restic/caddy
- import: 
  - client provide URI of the VM he wants to import
  - Restic supports fuse mount, we could use this to expose the exported VM locally in the new location and create and restor the vdisk of the VM from the files in restics.

**Comment by FastGeert** [comment]
After this FR was created, there has been decided that we would use FTP for exporting vdisks. So we will also use FTP(S) for exporting vms.

**Comment by Dinaamagdy** [comment]
Can't export VM and ays return this error : 

```
[Thu12 15:03] - Job.py              :68  :j.core.jobcontroller.job.7deede9a56927eb9b9e57db04f0fff0e - ERROR    - job: vdisk!vdisk3 (export) failed:
Traceback (most recent call last):
  File "/tmp/actions/vdisk/face1038f98d7c6653da594a1d3790ba.py", line 107, in export
    container.waitOnJob(container_job)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 257, in waitOnJob
    resp.stream(callback)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 234, in stream
    callback(meta >> 16, line, meta & 0xff)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 255, in callback
    raise RuntimeError(erroMessage)
RuntimeError: Flags:   -b, --blocksize int                 the size of the exported (deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to use, options { lz4, xz } (default lz4)       --conf
ig SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)   -f, --force                         when given, overwrite a deduped map if it can't be loaded   -h, --help            
              help for vdisk   -j, --jobs int                      the amount of parallel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-size private key used for encryption when given (def
ault )   -s, --storage StorageConfig         ftp server url or local dir path to export the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available information  error while processing block: unexpect
ed LIST response: [] 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/face1038f98d7c6653da594a1d3790ba.py", line 110, in export
    raise RuntimeError("Failed to export vdisk %s: %s", (service.name, strerror))
RuntimeError: ('Failed to export vdisk %s: %s', ('vdisk3', "Flags:   -b, --blocksize int                 the size of the exported (deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to use, 
options { lz4, xz } (default lz4)       --config SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)   -f, --force                         when given, overwrite a deduped map 
if it can't be loaded   -h, --help                          help for vdisk   -j, --jobs int                      the amount of parallel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-size p
rivate key used for encryption when given (default )   -s, --storage StorageConfig         ftp server url or local dir path to export the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available infor
mation  error while processing block: unexpected LIST response: [] "))
[Thu12 15:03] - Service.py          :729 :j.atyourservice.server.service - ERROR    - error during execute action: ('Failed to export vdisk %s: %s', ('vdisk3', "Flags:   -b, --blocksize int                 the size of the exported 
(deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to use, options { lz4, xz } (default lz4)       --config SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml 
file) (default config.yml)   -f, --force                         when given, overwrite a deduped map if it can't be loaded   -h, --help                          help for vdisk   -j, --jobs int                      the amount of par
allel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-size private key used for encryption when given (default )   -s, --storage StorageConfig         ftp server url or local dir path to exp
ort the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available information  error while processing block: unexpected LIST response: [] "))
2017-10-12 15:03:11 - (network)[INFO][127.0.0.1:52412]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/8e1842f395a05ad24dba3bcb90ba8937  200 196
INFO:network:
[Thu12 15:03] - Job.py              :29  :j.core.jobcontroller.job.8e1842f395a05ad24dba3bcb90ba8937 - INFO     - job: vm!dina (processChange) took 17.469983339309692 sec to execute
[Thu12 15:03] - Job.py              :68  :j.core.jobcontroller.job.8e1842f395a05ad24dba3bcb90ba8937 - ERROR    - job: vm!dina (processChange) failed:
Traceback (most recent call last):
  File "/tmp/actions/vdisk/face1038f98d7c6653da594a1d3790ba.py", line 107, in export
    container.waitOnJob(container_job)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 257, in waitOnJob
    resp.stream(callback)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 234, in stream
    callback(meta >> 16, line, meta & 0xff)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 255, in callback
    raise RuntimeError(erroMessage)
RuntimeError: Flags:   -b, --blocksize int                 the size of the exported (deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to use, options { lz4, xz } (default lz4)       --conf
ig SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)   -f, --force                         when given, overwrite a deduped map if it can't be loaded   -h, --help            
              help for vdisk   -j, --jobs int                      the amount of parallel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-size private key used for encryption when given (def
ault )   -s, --storage StorageConfig         ftp server url or local dir path to export the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available information  error while processing block: unexpect
ed LIST response: [] 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/2164fb2fcd4f2003d774f2aebb1a653e.py", line 683, in processChange
    export(job)
  File "/tmp/actions/vm/2164fb2fcd4f2003d774f2aebb1a653e.py", line 97, in export
    vdisksrv.executeAction('export', context=job.context, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 727, in executeAction
    return futur.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
```

**Comment by Dinaamagdy** [comment]
```
Sun22 10:17] - Job.py              :68  :j.core.jobcontroller.job.7a60b4c2ddb0969668744c5a5e508c23 - ERROR    - job: vm!dinavm (processChange) failed:
Traceback (most recent call last):
  File "/tmp/actions/vdisk/60224c2eda2d37306e29d7082e66a69f.py", line 400, in export
    container.waitOnJob(container_job)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/Container.py", line 263, in waitOnJob
    resp.stream(callback)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 234, in stream
    callback(meta >> 16, line, meta & 0xff)
  File "/opt/code/github/zero-os/0-orchestrator/pyclient/zeroos/orchestrator/sal/Container.py", line 261, in callback
    raise RuntimeError(erroMessage)
RuntimeError: Flags:   -b, --blocksize int                 the size of the exported (deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to use, options { lz4, xz } (default lz4)       --conf
ig SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)   -f, --force                         when given, overwrite a deduped map if it can't be loaded   -h, --help            
              help for vdisk   -j, --jobs int                      the amount of parallel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-size private key used for encryption when given   -s
, --storage StorageConfig         ftp server url or local dir path to export the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available information  error while processing block: sent 91709 bytes, b
ut size is 0 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/bb8731a3db60f5a267109c5ec00d6a04.py", line 235, in processChange
    export(job)
  File "/tmp/actions/vm/bb8731a3db60f5a267109c5ec00d6a04.py", line 886, in export
    vdisk_service.executeAction('export', context=job.context, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 728, in executeAction
    return futur.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112750)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 759, in _executeActionJob
    result = await job.execute()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110832)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114026)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/60224c2eda2d37306e29d7082e66a69f.py", line 403, in export
    raise RuntimeError("Failed to export vdisk %s: %s", (service.name, strerror))
RuntimeError: ('Failed to export vdisk %s: %s', ('vdiskdina2', "Flags:   -b, --blocksize int                 the size of the exported (deduped) blocks (default 131072)   -c, --compression CompressionType   the compression type to u
se, options { lz4, xz } (default lz4)       --config SourceConfig           config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)   -f, --force                         when given, overwrite a deduped 
map if it can't be loaded   -h, --help                          help for vdisk   -j, --jobs int                      the amount of parallel jobs to run (default 48)   -k, --key AESCryptoKey              an optional 32 byte fixed-si
ze private key used for encryption when given   -s, --storage StorageConfig         ftp server url or local dir path to export the backup to (default /.zero-os/nbd/vdisks)  Global Flags:   -v, --verbose   log available information 
 error while processing block: sent 91709 bytes, but size is 0 "))
2017-10-22 10:17:14 - (network)[INFO][127.0.0.1:58168]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/7a60b4c2ddb0969668744c5a5e508c23  200 7505
INFO:network:
2017-10-22 10:17:14 - (network)[INFO][127.0.0.1:58168]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/7a60b4c2ddb0969668744c5a5e508c23  200 7505
INFO:network:
2017-10-22 10:17:16 - (network)[INFO][127.0.0.1:58168]: PUT http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/vm_dinavm_export_1508667366/archive  200 56

```

**Comment by khaledkbadr** [comment]
Can't reproduce, I used proftp server with the below configuration
```
Include /etc/proftpd/modules.conf
UseIPv6				on
IdentLookups			off
ServerName			"Debian"
ServerType			standalone
DeferWelcome			off
MultilineRFC2228		on
DefaultServer			on
ShowSymlinks			on
TimeoutNoTransfer		600
TimeoutStalled			600
TimeoutIdle			1200
DisplayLogin                    welcome.msg
DisplayChdir               	.message true
ListOptions                	"-l"
DenyFilter			\*.*/
Port				21
<IfModule mod_dynmasq.c>
# DynMasqRefresh 28800
</IfModule>
MaxInstances			30
User				proftpd
Group				nogroup
Umask				022  022
# Normally, we want files to be overwriteable.
AllowOverwrite			on
TransferLog /var/log/proftpd/xferlog
SystemLog   /var/log/proftpd/proftpd.log
<IfModule mod_quotatab.c>
QuotaEngine off
</IfModule>
<IfModule mod_ratio.c>
Ratios off
</IfModule>
<IfModule mod_delay.c>
DelayEngine on
</IfModule>
<IfModule mod_ctrls.c>
ControlsEngine        off
ControlsMaxClients    2
ControlsLog           /var/log/proftpd/controls.log
ControlsInterval      5
ControlsSocket        /var/run/proftpd/proftpd.sock
</IfModule>
<IfModule mod_ctrls_admin.c>
AdminControlsEngine off
</IfModule>
<Anonymous ~ftp>
  User				ftp
  Group				nogroup
  # We want clients to be able to login with "anonymous" as well as "ftp"
  UserAlias			anonymous ftp
  # Cosmetic changes, all files belongs to ftp user
  DirFakeUser	on ftp
  DirFakeGroup on ftp

  RequireValidShell		off

  # Limit the maximum number of anonymous logins
  MaxClients			10

  # We want 'welcome.msg' displayed at login, and '.message' displayed
  # in each newly chdired directory.
  DisplayLogin			welcome.msg
  DisplayChdir		.message

  # Limit WRITE everywhere in the anonymous chroot
# <Directory *>
#  <Limit WRITE>
#    DenyAll
#  </Limit>
# </Directory>
</Anonymous>

# Include other custom configuration files
Include /etc/proftpd/conf.d/
```
