### ISSUE TITLE
Creating a container with vlan config without OVS is returning 500

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#563]
**Steps:**
- Make sure that there is no OVC
- Try to create a container or a GW with vlan config

**API**
POST http://10.147.17.92:8080/nodes/0cc47ae54380/gws
**Payload**
```json
{
  "name":"gw_23",
  "domain":"tester",
  "nics":[
    {
      "name":"public",
      "type":"vlan",
      "id":"0",
      "config":{
        "cidr":"172.18.0.10/24",
        "gateway":"172.18.0.1"
      }
    },
    {
      "name":"private",
      "type":"vxlan",
      "id":"200",
      "config":{
        "cidr":"192.168.112.22/24"
      },
      "dhcpserver":{
        "nameservers":[
          "8.8.8.8"
        ],
        "hosts":[
          {
            "macaddress":"00:A0:C9:14:C8:29",
            "hostname":"sarah",
            "ipaddress":"192.168.112.11"
          }
        ]
      }
    }		
  ]
}
```

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/27768840-1d4cdc40-5f1d-11e7-9620-6ab1ea323ca7.png)

**AYS error**
```bash
[Sun02 09:40] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Sun02 09:40] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e2369443bd7dbed2d0b560d444236ed3
Error of job: container!gw_23 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/e39831f7f4c3dce6ace0a49579668064.py", line 50, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/e39831f7f4c3dce6ace0a49579668064.py", line 60, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 170, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 163, in _create_container
    raise RuntimeError('failed to create container %s' % result.data)
RuntimeError: failed to create container "ovs is needed for VLAN network type"
```

**Expected result**
It should return bad request

**Comment by zaibon** [comment]
Relates to https://github.com/zero-os/0-core/issues/459

We probably should check in the init of the service that if we have nics with vlan defined. We check if the OVS container exists and it's running.

**Comment by Dinaamagdy** [comment]
blocked due to 
https://github.com/zero-os/0-orchestrator/issues/724

**Comment by Dinaamagdy** [comment]
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091
