### ISSUE TITLE
make grafana service

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#579]
Create service which autoconsumes existing influxdb and configured datassources.

On top of this we can create a dashboard service

**Comment by ahmedelsayed-93** [comment]
#### influxdb blueprint
```yaml
influxdb__test:
  node: '248a07e3ca90'
  databases:
  - 'aysone'
  - 'aystwo'
```
#### grafana blueprint
```yaml
grafana__statsdb:
  node: '248a07e3ca90'
  port: 3000
  influxdb:
    - test

actions:
 - action: install
```

### result 

![image](https://user-images.githubusercontent.com/24386820/27993027-5100bf00-64a1-11e7-92c6-c4982434cc26.png)

### error 
```
[Sun09 10:18] - Job.py              :57  :j.core.jobcontroller.job.74cfaddbb7930f9409752948094df1de - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/influxdb/bc97110a7affa58a2cd243ca76dc8ccd.py", line 115, in start
    influx.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/influxdb/influxdb.py", line 73, in start
    self.container.node.client.nft.drop_port(self.port)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2016, in drop_port
    return self._client.json('nft.drop_port', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 597, in json
    result = self.sync(command, arguments)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 587, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"rule \"tcp dport 8086 accept\" not found"
)
````

### software version
master : e972825

**Comment by Dinaamagdy** [comment]
## Software Version 
2ce75f13c3138bbe34c088d95c1be00bbbbfa6c7
