### ISSUE TITLE
Delete   service doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#587]
## Scenario 
After delete  Gw and for some reason its child container still exist ,I try to delete bridge it doesn't work as shown : 

![selection_431](https://user-images.githubusercontent.com/24386802/27798469-a2537760-6011-11e7-8f2d-d2b428c0b561.png)

## Error
```
vice:bridge!e0f18644f                                                                                      [6/1871]
init done
blueprint done
2017-07-03 15:01:59 - (network)[INFO][127.0.0.1:36648]: POST http://127.0.0.1:5000/ays/repository/orchestrator-serv
er/blueprint/bridge_e0f18644f_delete_1499094112  200 86
INFO:network:
2017-07-03 15:02:00 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 365, in serviceGet
    return self.db.services.services[key]
KeyError: 'bdcb4af0cdf841039789c3af44084f5f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 66, in post
    return await auth(request, ays_api.createRun(request, repository))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 258, in createRun
    to_execute = repo.findScheduledActions()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 632, in findScheduledActi
ons
    if is_producer_in_error(service, action):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 611, in is_producer_in_er
ror
    for producers in service.producers.values():
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 394, in producers
    producers[role].append(self.aysrepo.serviceGet(key=prod.key))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 367, in serviceGet
    raise j.exceptions.NotFound('cant find service with key %s' % key)
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: cant find service with key bdcb4af0cdf841039789c3af44084f5f 
((type:notfound)

ERROR:sanic:Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 365, in serviceGet
    return self.db.services.services[key]
KeyError: 'bdcb4af0cdf841039789c3af44084f5f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 66, in post
    return await auth(request, ays_api.createRun(request, repository))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 258, in createRun
    to_execute = repo.findScheduledActions()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 632, in findScheduledActi
ons
    if is_producer_in_error(service, action):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 611, in is_producer_in_er
ror
    for producers in service.producers.values():
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 394, in producers
    producers[role].append(self.aysrepo.serviceGet(key=prod.key))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 367, in serviceGet
    raise j.exceptions.NotFound('cant find service with key %s' % key)
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: cant find service with key bdcb4af0cdf841039789c3af44084f5f 
((type:notfound)

2017-07-03 15:02:00 - (network)[INFO][127.0.0.1:36652]: POST http://127.0.0.1:5000/ays/repository/orchestrator-serv
er/aysrun  500 144
```

**Comment by zaibon** [comment]
Mark as known issue for alpha-5 and moved to alpha-6

**Comment by Dinaamagdy** [comment]
the Update scenario which repoduce it  : 
- delete cloudspace which have running vms . 
## Error
```
    return self.db.services.services[key]                                                                                                                                                                                    [450/1083]
KeyError: '7af9319361abcad9599bec76c498e5be'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.zero-os/aa09f45f5dc5532d7a31268ea4c8c2d9.py", line 326, in monitor
    stats_collector_service = get_stats_collector(service)
  File "/tmp/actions/node.zero-os/aa09f45f5dc5532d7a31268ea4c8c2d9.py", line 293, in get_stats_collector
    stats_collectors_services = service.consumers.get('stats_collector')
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 413, in consumers
    consumers[role].append(self.aysrepo.serviceGet(key=cons.key))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 340, in serviceGet
    raise j.exceptions.NotFound('cant find service with key %s' % key)
JumpScale9.errorhandling.JSExceptions.NotFound: ERROR: cant find service with key 7af9319361abcad9599bec76c498e5be ((type:notfound)
```

**Comment by Dinaamagdy** [comment]
## Software Version 
7a2ef4e39ab2e7a825d2e92b35d022f3508f15e3
