### ISSUE TITLE
Selfhealing: VM faire use policy

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#617]
Implement in VM service monitor action.

Checks cpu time and quratines machine according to fair use policy .
If average per 5 min is higher than threshold a warning is sent via email.
if over use presists for longer than warntime  the machine is quarantined to a limit,
this is done for a quarantine time and then unquarantined .
if quarantined again after unquarantine quarantine time doubles for each time.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/vm_cpu_fair_use_policy.py

**Comment by serboctor** [comment]
We also need to log messages whenever a VM starts approaching the fair usage thresholds. These messages can then be parsed by the watchdog and added to the health checks.

**Comment by serboctor** [comment]
@zaibon suggested that the user email becomes part of the jwt token and is saved in the service of the vm. And we agreed that ork can log a message when a vm is in a warning state. The watchdog handler will then react to the log message by sending a warning email to the user. @FastGeert any comments on this approach?

**Comment by zaibon** [comment]
After some extra thinking I don't think 0-orch should be aware of users. It's something the layer above the 0-ochestrator should do.

so the new proposal is that openvlcoud expose some kind of webhooks which 0-orch call send requests to when we it detects an abuse.

So the flow would be
-  ork detect an abuse
- ork write logs
- 0-orch read the log and send requests on configured webhook to notify openvloud somehing is wrong

So openvcloud would be the one sending email. Cause it knows which vms belongs to which customer.

**Comment by serboctor** [comment]
@grimpy thinks an event stream might be more ideal. Pending on @grimpy's final input on this.

**Comment by serboctor** [comment]
Sending emails or having live warnings in the health-checks is currently blocked on this https://github.com/zero-os/0-orchestrator/issues/985. Everything else has been implemented.

**Comment by Dinaamagdy** [comment]
## Steps 
- create node in packet with master cor0
- create vm in node with all available cpu(48) and with ubuntue template
- increase all cpu utilization to more than  80%
# Issue 
nothing happen at all for vm cpus number 
## Software version 
319d4ed64625cfb486363eae82d28df9d186441a

**Comment by rkhamis** [comment]
should be fixed in 8b1d080d91a6b4d9787d5b2f392da7653c7982a5

**Comment by Dinaamagdy** [comment]
blocked due to https://github.com/zero-os/0-orchestrator/issues/1044

**Comment by Dinaamagdy** [comment]
## Steps 
- create node in be-scale-2 with alpha8 cor0
- create vm in node with all available cpu(15) and with ubuntue template
- increase all cpu utilization to more than  80% using stress tool 
```
stress -c 15
```
# Issue 
before any thing happen to number of cpus in vm ,ork kill nbd server of vm and ardb-server too so we lose the vm 
## Software version 
ffcdcb98d4b9545a8d6b5ad0c5c45081075f8bca

**Comment by serboctor** [comment]
I added the ability to disable certain monitoring so you can test fair usage on it own until the cpu monitoring is refactored.
Please test again but pass the following kernel params `ork=nomem,nocpu`.

**Comment by ahmedelsayed-93** [comment]
i used this kernel parameter ```ork=nomem,nocpu``` in the ipxe url
and after executing ```stress``` command the nbd server of the vm had been stopped and then ays produced this error 
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Service.executeAction() done, defined at /opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py:719> exception=ERROR: Failed to start nbdserver myvm ((type:runtime.error)>
Traceback (most recent call last):
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112704)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/b95ae02d1a0087f2464860f52771a01d.py", line 272, in start
    j.tools.async.wrappers.sync(service.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/b95ae02d1a0087f2464860f52771a01d.py", line 330, in install
    medias = _start_nbd(job)
  File "/tmp/actions/vm/b95ae02d1a0087f2464860f52771a01d.py", line 104, in _start_nbd
    j.tools.async.wrappers.sync(nbdserver.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/3af40249f1bb3783fe976b32943c74ad.py", line 245, in start
    j.tools.async.wrappers.sync(service.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/3af40249f1bb3783fe976b32943c74ad.py", line 175, in install
    raise j.exceptions.RuntimeError("Failed to start nbdserver {}".format(vm.name))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to start nbdserver myvm ((type:runtime.error)

```
