### ISSUE TITLE
Create script that generate storagecluster dashboard

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#634]
We need to have a script (later this needs to be automated) that generates a dashboard for a storagecluster.

This dashboard needs to contain a view on the disk usage and IOPS of all disks involved in the storagecluster.
Invidual and agregate view should be possible.

**Scenarios:**
* `statsdb` service is already deployed. Then when creating storage cluster it should generate its dashboard.
* `storage_cluster` already deployed. Then when deploying statsdb service it should also generate dashboard of storage clusters found.
* statsdb is not deployed at all. Then when deploying storage cluster dashboard shouldn't be generated at all

**Comment by Dinaamagdy** [comment]
-After run statsdb service  ,can't create storagecluster with this error :
```
[Wed12 10:09] - Job.py              :57  :j.core.jobcontroller.job.7b134b012036611b21a7cdd0db1d55dc - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/af80d71e4b39316d7caa3449407d309a.py", line 169, in init
    cluster = get_cluster(job)
  File "/tmp/actions/storage_cluster/af80d71e4b39316d7caa3449407d309a.py", line 71, in get_cluster
    return StorageCluster.from_ays(job.service, job.context['token'])
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 36, in from_ays
    storages_server = StorageServer.from_ays(storageEngine_service, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 157, in from_ays
    storageEngine = StorageEngine.from_ays(storageEngine_services, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageEngine.py", line 30, in from_ays
    container = Container.from_ays(service.parent, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 96, in from_ays
    sp = node.storagepools.get(fs_service.parent.name)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 59, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name cluster_248a07e3cc50_st_test_sdb
[Wed12 10:09] - ays_api.py          :476 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 Could not find StoragePool with name cluster_248a07e3cc50_st_test_sdb
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 462, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 484, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 32, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 25, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 138, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 628, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/af80d71e4b39316d7caa3449407d309a.py", line 169, in init
    cluster = get_cluster(job)
  File "/tmp/actions/storage_cluster/af80d71e4b39316d7caa3449407d309a.py", line 71, in get_cluster
    return StorageCluster.from_ays(job.service, job.context['token'])
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 36, in from_ays
    storages_server = StorageServer.from_ays(storageEngine_service, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageCluster.py", line 157, in from_ays
    storageEngine = StorageEngine.from_ays(storageEngine_services, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageEngine.py", line 30, in from_ays
    container = Container.from_ays(service.parent, password)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 96, in from_ays
    sp = node.storagepools.get(fs_service.parent.name)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 59, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name cluster_248a07e3cc50_st_test_sdb
2017-07-12 10:09:03 - (network)[INFO][127.0.0.1:33344]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/storage_cluster_st_test_install_1499854134  500 81

```

**Comment by Dinaamagdy** [comment]
## Software Version
2b48d48e8d08470aaf9e8c2217ec60eff4122358
