### ISSUE TITLE
storagecluster_apis: delete storagecluster doesn't cleanup the opened ports 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#644]
### ays error
```
Error of job: tcp!tcp_248a07e77520_2007 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/tcp/bd1a1e45c31da21bcd27a1f4faa88cfd.py", line 131, in install
    node.client.nft.open_port(service.model.data.port)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1989, in open_port
    return self._client.json('nft.open_port', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 597, in json
    result = self.sync(command, arguments)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 587, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"rule exists"
)

```

### software version
master : 92d0ba0

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 9ab91704
