### ISSUE TITLE
storagepools_apis: delete filesystem returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#658]
### API
```DELETE /nodes/{nodeid}/storagepools/{storagepoolname}/filesystems/{filesystemname}```

![image](https://user-images.githubusercontent.com/24386820/27993752-250fe5ba-64b0-11e7-97db-2f6759639fcc.png)

### ays log
```python
[Sun09 12:08] - RunStep.py          :69  :j.atyourservice.server         - INFO     - execute job: filesystem!fs1 (delete)
[Sun09 12:08] - Job.py              :67  :j.core.jobcontroller.job.7087577719efad8d963e9ea278ab67b2 - INFO     - job job: node.zero-os!248a07e641f0 (monitor) done sucessfuly
[Sun09 12:08] - Job.py              :67  :j.core.jobcontroller.job.80277e320a8b6c5322e3b8705e624196 - INFO     - job job: node.zero-os!248a07e3cbe0 (monitor) done sucessfuly
[Sun09 12:08] - Job.py              :57  :j.core.jobcontroller.job.cd4bbad7766ae047b914ad7c56b4c448 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/filesystem/4d509adaeab4589348b48cb143df0ada.py", line 14, in delete
    fs.delete()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 313, in delete
    paths = [fs['Path'] for fs in self._client.btrfs.subvol_list(self.path)]
TypeError: 'NoneType' object is not iterable
[Sun09 12:08] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 3: error
[Sun09 12:08] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 3 in run 7fc601dabb2a0de479f6e09d0d53612d
Error of job: filesystem!fs1 (delete):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/filesystem/4d509adaeab4589348b48cb143df0ada.py", line 14, in delete
    fs.delete()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StoragePool.py", line 313, in delete
    paths = [fs['Path'] for fs in self._client.btrfs.subvol_list(self.path)]
TypeError: 'NoneType' object is not iterable

```

### software version
master : e972825

**Comment by serboctor** [comment]
Refactored self._client.btrfs.subvol_list to return an empty list instead of None.
This change was done in core0 and its python client.

**Comment by ahmedelsayed-93** [comment]
### software version
master : ee1db4d9
