### ISSUE TITLE
Can't create vm 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#662]
when I am trying create vm , it gives internal server error   then ays stop working : 
## Request body :
image : "ardb://hub.gig.tech:16379/template:ubuntu-1604"
```
{
  "id": "vm_test",
  "memory": 1024,
  "cpu": 1,
	"disks": [
    {
      "vdiskid": "vdisk_test",
      "maxIOps": 2000
    }
  ],
  "userCloudInit": null,
  "systemCloudInit": null
}
```
## Error 
```
{
	"error": "Failed to check for conflicting services"
}
```

## AYS Error 
```
INFO:network:
[Sun09 11:54] - Job.py              :57  :j.core.jobcontroller.job.a30eba5d3dd60afea7d99750f3820be2 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/f2e7fd8ff5b86839a352eae739a914dc.py", line 456, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1683, in create
    self._create_chk.check(args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 246, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 217, in _check_dict
    self._check(attr_type, value, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 120, in check
    self._checker.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 238, in _check
    self._check_list(typ[0], object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 207, in _check_list
    self._check(typ, elem, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 246, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 217, in _check_dict
    self._check(attr_type, value, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> //media/[0]/iotune
  -> [invalid type, expecting <class 'int'>] at -> //media/[0]/iotune/sizeiopssec
  -> [is not missing] at -> //media/[0]/iotune
2017-07-09 11:54:06 - (sanic)[INFO]: Stopping worker [17419]
INFO:sanic:Stopping worker [17419]
[Sun09 11:54] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 4: ok
2017-07-09 11:54:06 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 450, in serve
    loop.run_forever()
 File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)                                                              [106/1819]
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 311, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10730)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "uvloop/future.pyx", line 448, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:114340)
  File "uvloop/future.pyx", line 441, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114043)
  File "uvloop/future.pyx", line 383, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:113654)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/f2e7fd8ff5b86839a352eae739a914dc.py", line 456, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1683, in create
    self._create_chk.check(args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 246, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 217, in _check_dict
    self._check(attr_type, value, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 120, in check
    self._checker.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 238, in _check
    self._check_list(typ[0], object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 207, in _check_list
    self._check(typ, elem, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 246, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 217, in _check_dict
    self._check(attr_type, value, tx)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> //media/[0]/iotune
  -> [invalid type, expecting <class 'int'>] at -> //media/[0]/iotune/sizeiopssec
  -> [is not missing] at -> //media/[0]/iotune
ERROR:sanic:Experienced exception while trying to serve
```
## Orchestrator: 
```
2017/07/09 11:54:07 http: panic serving 172.27.222.222:54332: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc420392000)
        /opt/jumpscale9/go/root/src/net/http/server.go:1721 +0xd0
panic(0x893180, 0xb5d230)
        /opt/jumpscale9/go/root/src/runtime/panic.go:489 +0x2cf
github.com/zero-os/0-orchestrator/api/tools.WaitOnRun(0xb37640, 0xc420374a20, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400, 0xc4200c6e80, 0x20, 0x914207, 0x7, 0xc4200f80f0, ...)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/runs.go:40 +0x2e0
github.com/zero-os/0-orchestrator/api/node.NodeAPI.CreateVM(0x7ffe01cbf927, 0x13, 0x7ffe01cbf906, 0x15, 0xc42000e1d0, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_api_CreateVM.go:71 +0x81a
github.com/zero-os/0-orchestrator/api/node.(*NodeAPI).CreateVM(0xc4200f95f0, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400)
        <autogenerated>:77 +0x87
github.com/zero-os/0-orchestrator/api/node.(NodesInterface).CreateVM-fm(0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_if.go:423 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc42034b1a0, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420059090, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a400)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/zero-os/0-orchestrator/api/tools.(*Oauth2itsyouonlineMiddleware).Handler.func1(0x7f7d44a920c8, 0xc4201667e0, 0xc42038a300)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/oauth2_itsyouonline_middleware.go:124 +0x253
net/http.HandlerFunc.ServeHTTP(0xc420114d20, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a300)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420118380, 0x7f7d44a920c8, 0xc4201667e0, 0xc42038a200)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:68 +0x117
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb33f00, 0xc42000e020, 0xb33180, 0xc420118380, 0xb388c0, 0xc4200ec380, 0xc42038a200)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420114d40, 0xb388c0, 0xc4200ec380, 0xc42038a200)
        <autogenerated>:8 +0x86
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420059040, 0xb388c0, 0xc4200ec380, 0xc42038a200)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc420201970, 0xb388c0, 0xc4200ec380, 0xc42038a000)
        /opt/jumpscale9/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420392000, 0xb39180, 0xc420128140)
        /opt/jumpscale9/go/root/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /opt/jumpscale9/go/root/src/net/http/server.go:2668 +0x2ce
ERRO[0319] Get http://127.0.0.1:5000/ays/repository/orchestrator-server/service/vm/uvm: dial tcp 127.0.0.1:5000: getsockopt: connection refused 
172.27.222.222 - - [09/Jul/2017:11:54:08 +0000] "POST /nodes/248a07e64220/vms HTTP/1.1" 500 53
```
## Software Version 
e9728253d4db5aeb17038e5030f06c06ae762b5c

**Comment by Dinaamagdy** [comment]
## Software Version 
2ce75f13c3138bbe34c088d95c1be00bbbbfa6c7
