### ISSUE TITLE
implement error/stdout feedback mechanism to AYS

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-orchestrator#666]

**Comment by Dinaamagdy** [comment]
ays throw this error in watchdog in execution  process like creation of vm  ,then it doesn't work 

```
[Mon31 11:41] - Job.py              :56  :j.core.jobcontroller.job.e73be49105ca2b785132c60538ee94bd - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/tmp/actions/node.zero-os/f3f606e0fa7524d9dc4ecdf4b22032b1.py", line 391, in streaming
    queue = await cl.subscribe('ays.monitor')
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 137, in subscribe
    response = await self.sync('logger.subscribe', {'queue': queue})
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 125, in sync
    response = await self.raw(command, args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 114, in raw
    self._redis = await self.get()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 73, in get
    timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/commands/__init__.py", line 148, in create_redis
    loop=loop)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/connection.py", line 77, in create_connection
    host, port, ssl=ssl, loop=loop), timeout, loop=loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 385, in wait_for
    yield from waiter
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
RuntimeError: Task <Task pending coro=<watchdog.<locals>.streaming() running at /tmp/actions/node.zero-os/f3f606e0fa7524d9dc4ecdf4b22032b1.py:391> cb=[_execute_cb(job: node.zer...340 (watchdog))() at /opt/code/github/jumpscale/ays$/JumpScale9AYS/jobcontroller/Job.py:18, Task._wakeup()]> got Future <Future pending> attached to a different loop
2017-07-31 11:41:30 - (network)[INFO][127.0.0.1:59256]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/aysrun/69e8b9e567f36e541209488b86a74312  200 1265
INFO:network:
```

**Comment by ahmedelsayed-93** [comment]
after killing the process of the NBD server, ays didn't restart the process again
### software version
master : 2043f538

**Comment by ahmedelsayed-93** [comment]
https://github.com/zero-os/0-orchestrator/issues/489

**Comment by Dinaamagdy** [comment]
Now sometimes get this error then watchdog doesn't work 
```
Sun06 15:36] - d39d1018e799a58129455f1f9ed76162.py:221 :j.core.jobcontroller.job.4020230ff7c5c830cf060e6c21db1424 - ERROR    - Task <Task pending coro=<watchdog.
<locals>.streaming() running at /tmp/actions/node.zero-os/d39d1018e799a58129455f1f9ed76162.py:208> cb=[_execute_cb(job: node.zer...250 (watchdog))() at /opt/code/
github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py:18, Task._wakeup()]> got Future <Future pending> attached to a different loop

```
## Software Version 
5cfc4d99b8c58fce0596a1e9551e1a2fefcac1d7

**Comment by Dinaamagdy** [comment]
## Software Version 
012719ca7375c9a5ba500bc403a61a15b0873b53
