### ISSUE TITLE
storagepool_apis : create filesystem snapshot returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#687]
### API
```POST  /nodes/{nodeid}/storagepools/{storagepoolname}/filesystems/{filesystemname}/snapshots```

### api request

![image](https://user-images.githubusercontent.com/24386820/28075651-61790cea-665c-11e7-9828-db88393acdd1.png)

### ays log
```
[Tue11 15:12] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Tue11 15:12] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run dad8fa3c9f60e6b0bbd2bfb069c90eae
Error of job: fssnapshot!sn1 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/fssnapshot/ce95e5c78dfc58ac8d27bb56d9dd9a65.py", line 118, in install
    fs = get_filesystem(job)
  File "/tmp/actions/fssnapshot/ce95e5c78dfc58ac8d27bb56d9dd9a65.py", line 20, in get_filesystem
    fsname = str(job.ervice.parent.model.data.name)
AttributeError: 'Job' object has no attribute 'ervice'

```

### software version
master : c8730c23

**Comment by Dinaamagdy** [comment]
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091
