### ISSUE TITLE
Ays crash when restart VM 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#692]
## Steps 
- create vm
- stop vm
- start vm again
- rollback vdisk

## Error 
Ays crash and can't start it again : 

```
[Wed12 09:22] - Job.py              :67  :j.core.jobcontroller.job.625634e00a1ce5e38d8758b47ae835c7 - INFO     - job job: bootstrap.zero-os!grid1 (bootstrap) done sucessfuly                                                [393/1909]
[Wed12 09:22] - Job.py              :57  :j.core.jobcontroller.job.3c5d39741a04354c74be81bf0a092682 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 263, in monitor
    running = is_job_running(get_container(service, get_jwt_token(job.service.aysrepo)))
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 40, in is_job_running
    for job in container.client.job.list():
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 136, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1007, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /
2017-07-12 09:22:47 - (sanic)[INFO]: Stopping worker [10767]
INFO:sanic:Stopping worker [10767]
2017-07-12 09:22:47 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 450, in serve
    loop.run_forever()
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 311, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10730)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "uvloop/future.pyx", line 448, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:114340)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 263, in monitor
    running = is_job_running(get_container(service, get_jwt_token(job.service.aysrepo)))
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 40, in is_job_running
    for job in container.client.job.list():
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 136, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1007, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /
ERROR:sanic:Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 450, in serve
    loop.run_forever()
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 311, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10730)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "uvloop/future.pyx", line 448, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:114340)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run                                                                                                                                                    [325/1909]
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 263, in monitor
    running = is_job_running(get_container(service, get_jwt_token(job.service.aysrepo)))
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 40, in is_job_running
    for job in container.client.job.list():
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 136, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1007, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 70, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 450, in serve
    loop.run_forever()
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 311, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10730)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "uvloop/future.pyx", line 448, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:114340)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 263, in monitor
    running = is_job_running(get_container(service, get_jwt_token(job.service.aysrepo)))
  File "/tmp/actions/nbdserver/9dbf07c5d96907660d4ce8b443204e64.py", line 40, in is_job_running
    for job in container.client.job.list():
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 136, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1007, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /
**ERROR**
```

**Comment by Dinaamagdy** [comment]
now ays doesn't crash but it still give error in ays and vm status halted 
```

******************************************************************************************

Error of job: nbdserver!vmtest2 (start):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/c032343cd4ed2f9279bd8080a2eaadfd.py", line 14, in start
    j.tools.async.wrappers.sync(service.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/c032343cd4ed2f9279bd8080a2eaadfd.py", line 254, in install
    container.client.filesystem.upload(configpath, configstream)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 139, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1007, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /


******************************************************************************************
```

**Comment by FastGeert** [comment]
Accicdentally pressed "Closed" button.

**Comment by Dinaamagdy** [comment]
## Software Version
2b48d48e8d08470aaf9e8c2217ec60eff4122358
