### ISSUE TITLE
can't create gateway 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#724]
## Request 
{
  "name": "test",
  "domain": "test",
  "nics": [
    {
      "name": "public",
      "type": "vlan",
      "id": "200",
      "config": {
        "cidr": "217.200.205.5/24",
        "gateway": "217.200.205.2"
      }
    },
    {
      "name": "private",
      "type": "vxlan",
      "id": "2000",
      "config": {
        "cidr": "192.169.5.4/24"
      }
		}
        ]
}

## Error  
```
[Mon17 12:08] - Job.py              :57  :j.core.jobcontroller.job.7e425979b7c0fc2527455d9d006fd5bd - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 72, in start
    apply_config(job, gwdata)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 134, in apply_config
    dhcp.apply_config()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/gateway/dhcp.py", line 40, in apply_config
    raise RuntimeError('Failed to run dnsmasq')
RuntimeError: Failed to run dnsmasq
2017-07-17 12:08:33 - (network)[INFO][127.0.0.1:39326]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/aysrun/d751be2d8552df906db301afde51cd57  200 584
INFO:network:
[Mon17 12:08] - Job.py              :67  :j.core.jobcontroller.job.63ad116624943dfac73ffb3c66eda468 - INFO     - job job: bootstrap.zero-os!grid1 (bootstrap) done sucessfuly
[Mon17 12:08] - Job.py              :57  :j.core.jobcontroller.job.ace818e9634e179aadc24b5faa040867 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/d9ce591b7a6bdc84b75d6c5f561cc506.py", line 178, in start
    j.tools.async.wrappers.sync(dhcp.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 72, in start
    apply_config(job, gwdata)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 134, in apply_config
    dhcp.apply_config()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/gateway/dhcp.py", line 40, in apply_config
    raise RuntimeError('Failed to run dnsmasq')
RuntimeError: Failed to run dnsmasq
[Mon17 12:08] - Job.py              :57  :j.core.jobcontroller.job.efdaaa6113f2b2008c22bd61e4be6bc5 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/d9ce591b7a6bdc84b75d6c5f561cc506.py", line 247, in install
    j.tools.async.wrappers.sync(service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 72, in start
    apply_config(job, gwdata)
  File "/tmp/actions/dhcp/ac0d3f02287e0d85b62f7910a221fe6b.py", line 134, in apply_config
    dhcp.apply_config()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/gateway/dhcp.py", line 40, in apply_config
    raise RuntimeError('Failed to run dnsmasq')
RuntimeError: Failed to run dnsmasq
```
## Software version 
6bbe22687b399d93693d56c68d3abad11d236a97

**Comment by zaibon** [comment]
See https://github.com/zero-os/0-core/issues/459

**Comment by Dinaamagdy** [comment]
it still give internal server error with 500 status code , not fail
## Software Version 
67468454713d48e2e4a17bdee3fbe6e1c41e2080

**Comment by ashraffouda** [comment]
it will return bad request if ovs is not running

**Comment by ashraffouda** [comment]
![screenshot from 2017-08-15 18-06-11](https://user-images.githubusercontent.com/1689456/29324516-fb949d16-81ec-11e7-9448-bd3f13c86973.png)

**Comment by Dinaamagdy** [comment]
now it result this error although for same node I can create container ,vdisks and vms  : 
```
 File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/98cf572137b09d6eabbd6aa36498e612.py", line 227, in init
    node = Node.from_ays(service.parent)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 36, in from_ays
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 20, in __init__
    self._client = Client(host=addr, port=port, password=password, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2555, in __init__
    raise RuntimeError("Could not connect to remote host %s" % host)
RuntimeError: Could not connect to remote host 172.22.182.35
[Wed16 09:02] - Job.py              :56  :j.core.jobcontroller.job.f39735793ae3d55eee7b977053402821 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/bb955e4572ef748a65b264170b89e66b.py", line 330, in init
    cont_service = containeractor.serviceCreate(instance=service.name, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 526, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args, context=context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 518, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 143, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in init
    await job.executeInProcess()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/98cf572137b09d6eabbd6aa36498e612.py", line 227, in init
    node = Node.from_ays(service.parent)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 36, in from_ays
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 20, in __init__
    self._client = Client(host=addr, port=port, password=password, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2555, in __init__
    raise RuntimeError("Could not connect to remote host %s" % host)
RuntimeError: Could not connect to remote host 172.22.182.35
[Wed16 09:02] - ays_api.py          :476 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 Could not connect to remote host 172.22.182.35
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 462, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    msg = await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 154, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 518, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
 File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 143, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/bb955e4572ef748a65b264170b89e66b.py", line 330, in init
    cont_service = containeractor.serviceCreate(instance=service.name, args=args)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 526, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args, context=context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 518, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 26, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 143, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 673, in init
    await job.executeInProcess()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/98cf572137b09d6eabbd6aa36498e612.py", line 227, in init
    node = Node.from_ays(service.parent)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 36, in from_ays
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Node.py", line 20, in __init__
    self._client = Client(host=addr, port=port, password=password, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2555, in __init__
    raise RuntimeError("Could not connect to remote host %s" % host)
RuntimeError: Could not connect to remote host 172.22.182.35
```
## Software Version 
108e1ac0d6769d5dc65b2ca20503d8b22ea5f40c

**Comment by ashraffouda** [comment]
there was anothe problem that not related to the gateway itself, fixed

**Comment by Dinaamagdy** [comment]
## Software Version 
https://github.com/zero-os/0-orchestrator/issues/563
