### ISSUE TITLE
JS9 container failed to start after 0-orchestrator installation

### ISSUE THREAD

**Issue by arahmanhamdy** [zero-os/0-orchestrator#731]
Related issue: https://github.com/Jumpscale/developer/issues/67

Installation information

    jumpscale version: 9.0.3
    orchestrator version: master
    operating system: Ubuntu 16.04

Detailed description

When trying to start the docker after stopping it, it exits after 6 seconds
Steps to reproduce

    Install js9 docker
    Install 0-orchestrator
    Stop docker
    Start docker

I think the main reason for this bug is the `10_ays.sh` script in the `my_init.d` directory which created during the installation process: https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh#L159

As the environment at this time isn't fully initialized

start fail logs:

```
2017-07-18 14:55:47 - (sanic)[INFO]: Goin' Fast @ http://127.0.0.1:5000
2017-07-18 14:55:47 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 398, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 354, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "main.py", line 56, in init_ays
    key_path = local_prefab.ssh.keygen(name='ays_repos_key').split(".pub")[0]
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabSSH.py", line 109, in keygen
    d = self.prefab.user.check(user)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabUser.py", line 82, in check
    _, d, _ = self.prefab.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 1222, in run
    cmd = self.replace(cmd)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 370, in replace
    args2 = self.getArgsDict()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 400, in getArgsDict
    for key, var in self.dir_paths.items():
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 294, in dir_paths
    env = self.initEnv(env=env)  # put the missing paths in there
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 253, in initEnv
    env["HOMEDIR"] = env["HOME"]
KeyError: 'HOME'

```

**Comment by khaledkbadr** [comment]
fixed in https://github.com/Jumpscale/prefab9/pull/32

**Comment by Dinaamagdy** [comment]
## Software Version 
108e1ac0d6769d5dc65b2ca20503d8b22ea5f40c
