### ISSUE TITLE
error when creating storagecluster

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#734]
```
[Wed19 08:56] - Service.py          :67  :j.atyourservice.server.service - INFO     - init service test from storage_cluster
[Wed19 08:57] - Job.py              :67  :j.core.jobcontroller.job.de545c6fd73d8fc018b94a3c5e5451eb - INFO     - job job: storage_cluster!test (input) done sucessfuly
[Wed19 08:57] - Job.py              :67  :j.core.jobcontroller.job.672ea4c0bf13d239a3e7f105f4206714 - INFO     - job job: node.zero-os!248a07e3cbe0 (monitor) done sucessfuly
[Wed19 08:57] - Job.py              :57  :j.core.jobcontroller.job.b7a9c215971a07a683bd96d9688176b8 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.zero-os/9308aff90bcf0357c38a1dfde1a4f55a.py", line 220, in monitor
    update_healthcheck(service, node.healthcheck.run(cont, 'openfiledescriptors'))
  File "/tmp/actions/node.zero-os/9308aff90bcf0357c38a1dfde1a4f55a.py", line 38, in update_healthcheck
    health.name = message['name']
KeyError: 'name'
2017-07-19 08:57:31 - (sanic)[ERROR]: NoneType

ERROR:sanic:NoneType

2017-07-19 08:57:31 - (network)[INFO][]: {}b'/ays/repository/orchestrator-server/blueprint/storage_cluster_test_install_1500454589'  408 22
INFO:network:
[Wed19 08:57] - Job.py              :40  :j.core.jobcontroller.job.20eaf17090bfc71d41d7d61f052643c3 - INFO     - job: storage_cluster!test (init) has been cancelled
[Wed19 08:57] - Job.py              :57  :j.core.jobcontroller.job.20eaf17090bfc71d41d7d61f052643c3 - ERROR    - Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py", line 37, in _execute_cb
    exception = future.exception()
  File "uvloop/future.pyx", line 157, in uvloop.loop.BaseFuture.exception (uvloop/loop.c:109433)
concurrent.futures._base.CancelledError
[Wed19 08:57] - ays_api.py          :476 :j.atyourservice.server         - ERROR    - Error during execution of the blueprint:
 
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 462, in executeBlueprint
    message=message)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 495, in blueprintExecute
    await bp.load(role=role, instance=instance, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 496, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 33, in init_from_actor
    raise e
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 25, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 142, in _initFromActor
    await self.init(context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 632, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 96, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108829)
concurrent.futures._base.CancelledError
2017-07-19 08:57:34 - (network)[INFO][127.0.0.1:41222]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/storage_cluster_test_install_1500454589  500 12
INFO:network:
2017-07-19 08:57:38 - (network)[INFO][127.0.0.1:41238]: PUT http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/storage_cluster_test_install_1500454589/archive  200 68
INFO:network:
[Wed19 08:57] - Job.py              :67  :j.core.jobcontroller.job.bb759a87f191bce4b711fc888fda09e2 - INFO     - job job: node.zero-os!248a07e3cbe0 (monitor) done sucessfuly
```

### software version
master : aeaba8ae

**Comment by Dinaamagdy** [comment]
## Software Versoin
67468454713d48e2e4a17bdee3fbe6e1c41e2080
