### ISSUE TITLE
Can't create Vdisk

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#738]
## Request

```
{
	"id": "vdisk_test2",
	"size": 10,
	"blocksize": 4096,
	"type": "boot",
	"templatevdisk": "ardb://hub.gig.tech:16379/template:ubuntu-1604",
	"readOnly": false,
	"storagecluster": "cl23"

}
```
## Error
```

Error of job: vdisk!vdisk_test2 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/f11fd56ecda5c596c68154da350c5978.py", line 213, in install
    raise j.exceptions.RuntimeError("Failed to run zeroctl copy {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl copy "template:ubuntu-1604" does n
ot exist
 Error: "template:ubuntu-1604" does not exist
Usage:
  zeroctl copy vdisk source_vdiskid target_vdiskid [target_cluster] [flags]
Flags:
      —config string   zeroctl config file (default "config.yml")
  -h, —help            help for vdisk
Global Flags:
  -v, —verbose   log available information
 ((type:runtime.error)
```
## Software version
7faeed68dc37804ae2229c52ceacfd04807c0f79

**Comment by khaledkbadr** [comment]
That was I updated the 0-disk flist with the latest master at this point. I reverted back the flist to alpha-5 for now until I investigate further

**Comment by Dinaamagdy** [comment]
## Software version 
7faeed68dc37804ae2229c52ceacfd04807c0f79
