### ISSUE TITLE
error when running performance script

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#783]
script https://github.com/zero-os/0-orchestrator/tree/master/tests/performance
```
INFO:[secure]:Creating new container...
 You can follow here: http://192.168.191.196:8080/nodes/0cc47a740632/containers/bptest_15011391165513997
INFO:[secure]:Cleaning up...
Traceback (most recent call last):
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 56, in test_fio_nbd
    mountVdisks(api, deployInfo, nodeIDs)
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 109, in mountVdisks
    deployInfo[nodeID]["nbdClientInfo"] = nbdClientConnect(api, nodeID, containername, nbdConfig)
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 353, in nbdClientConnect
    waitProcess(api, nbdClientCommand, jobid, nodeID, containername)
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 334, in waitProcess
    raise RuntimeError("Command %s failed to execute successfully. %s" % (command, res["stderr"]))
RuntimeError: Command {'name': '/bin/nbd-client', 'pwd': '', 'args': ['-N', 'testvdisk_15011390663503697', '-u', '/fs/0cc47a740636_fscache/fs_15011390503782008/server.socket.nbd_1501139058545642', '/dev/nbd0', '-b', '4096']} failed to execute successfully. Error: Cannot open NBD: No such file or directory
Please ensure the 'nbd' module is loaded.
Exiting.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 71, in test_fio_nbd
    raise RuntimeError(e)
RuntimeError: Command {'name': '/bin/nbd-client', 'pwd': '', 'args': ['-N', 'testvdisk_15011390663503697', '-u', '/fs/0cc47a740636_fscache/fs_15011390503782008/server.socket.nbd_1501139058545642', '/dev/nbd0', '-b', '4096']} failed to execute successfully. Error: Cannot open NBD: No such file or directory
Please ensure the 'nbd' module is loaded.
Exiting.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 378, in <module>
    test_fio_nbd()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 73, in test_fio_nbd
    cleanUp(api, nodeIDs, deployInfo)
  File "/tmp/performance_test/0-orchestrator/tests/performance/bd-performance.py", line 149, in cleanUp
    filenames = deployInfo[nodeID]["filenames"]
KeyError: 'filenames'
```

**Comment by Dinaamagdy** [comment]
## Software Version 
4fff9271b5d6edd62023c004717dc595d9f14a20
