### ISSUE TITLE
error in vdisk rollback

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#808]
### Scenario 
- create vdisk.
- resize the vdisk.
- rollback the vdisk.

## request
```json
{
	"id": "myvdisk",
	"size": 10,
	"blocksize": 4096,
	"type": "boot",
	"templatevdisk": "ardb://hub.gig.tech:16379/template:ubuntu-1604",
	"storagecluster": "mycluster",
	"tlogStoragecluster": "tlogStoragecluster"
}
```
### ays error
```
2017-08-01 11:05:02 - (network)[INFO][127.0.0.1:56290]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/560531f87e0f08da8f06b8070a972d3d  200 190                                                                                                                                          [13/1238]
INFO:network:
/bin/zeroctl restore vdisk myvdisk --config /config.yaml --end-timestamp 1501585387000000000 --k 1 --m 1
[Tue01 11:05] - Job.py              :56  :j.core.jobcontroller.job.9b260bc76de68ad02803c68f712fd71d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/bd28eea21a58f0cf63afd3b9cc8385ed.py", line 48, in rollback
    raise j.exceptions.RuntimeError("Failed to run zeroctl restore {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl restore nil last hash
 Error: nil last hash
Usage:
  zeroctl restore vdisk id [flags]
Flags:
      --config string              zeroctl config file (default "config.yml")
      --end-timestamp uint         end timestamp in nanosecond(default 0: until the end)
  -h, --help                       help for vdisk
      --k int                      K variable of erasure encoding (default 4)
      --m int                      M variable of erasure encoding (default 2)
      --nonce string               hex nonce used for encryption (default "37b8e8a308c354048d245f6d")
      --priv-key string            private key (default "12345678901234567890123456789012")
      --start-timestamp uint       start timestamp in nanosecond(default 0: since beginning)
      --storage-addresses string   comma seperated list of redis compatible connectionstrings (format: '<ip>:<port>[@<db>]', eg: 'localhost:16379,localhost:6379@2'), if given, these are used for all vdisks, ignoring the given config
Global Flags:
  -v, --verbose   log available information
 ((type:runtime.error)
2017-08-01 11:05:03 - (network)[INFO][127.0.0.1:56290]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/560531f87e0f08da8f06b8070a972d3d  200 190
INFO:network:
[Tue01 11:05] - Job.py              :56  :j.core.jobcontroller.job.560531f87e0f08da8f06b8070a972d3d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/bd28eea21a58f0cf63afd3b9cc8385ed.py", line 309, in processChange
    j.tools.async.wrappers.sync(service.executeAction('rollback', args={'timestamp': args['timestamp']}, context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 683, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 708, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/bd28eea21a58f0cf63afd3b9cc8385ed.py", line 48, in rollback
    raise j.exceptions.RuntimeError("Failed to run zeroctl restore {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl restore nil last hash
 Error: nil last hash
Usage:
  zeroctl restore vdisk id [flags]
Flags:
      --config string              zeroctl config file (default "config.yml")
      --end-timestamp uint         end timestamp in nanosecond(default 0: until the end)
  -h, --help                       help for vdisk
      --k int                      K variable of erasure encoding (default 4)
      --m int                      M variable of erasure encoding (default 2)
      --nonce string               hex nonce used for encryption (default "37b8e8a308c354048d245f6d")
      --priv-key string            private key (default "12345678901234567890123456789012")
      --start-timestamp uint       start timestamp in nanosecond(default 0: since beginning)
      --storage-addresses string   comma seperated list of redis compatible connectionstrings (format: '<ip>:<port>[@<db>]', eg: 'localhost:16379,localhost:6379@2'), if given, these are used for all vdisks, ignoring the given config
Global Flags:
  -v, --verbose   log available information
 ((type:runtime.error)
2017-08-01 11:05:05 - (network)[INFO][127.0.0.1:56290]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/560531f87e0f08da8f06
```

### software version
master : 91f54c9

**Comment by ashraffouda** [comment]
can not reproduce, working fine

**Comment by Dinaamagdy** [comment]
still return same error 
## Configuration : 
```
configurations:
  - key: '0-core-version'
    value: 'master'
  - key: 'js-version'
    value: '9.1.1'
  - key: 'gw-flist'
    value: 'https://hub.gig.tech/gig-official-apps/zero-os-gw-master.flist'
  - key: 'ovs-flist'
    value: 'https://hub.gig.tech/gig-official-apps/ovs.flist'
  - key: '0-disk-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-disk-master.flist'
  - key: '0-statscollector-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-statscollector-master.flist'
  - key: 'jwt-token'
```
## request:
```
{
  "id": "vdisk3",
  "size": 10,
  "blocksize": 4096,
  "type": "boot",
  "storagecluster": "st",
  "tlogStoragecluster":"tlog"
}
```
## Software Version 
108e1ac0d6769d5dc65b2ca20503d8b22ea5f40c

**Comment by ashraffouda** [comment]
@Dinaamagdy  tested on your environment everything is working fine 
as per discussion with Glen, rollback code doesn't care about size, it is about data

**Comment by ashraffouda** [comment]
![screenshot from 2017-08-16 14-37-03](https://user-images.githubusercontent.com/1689456/29363493-e606c738-8298-11e7-97d2-4fc1020692de.png)

**Comment by Dinaamagdy** [comment]
by this steps : 
- create vdisk
- create vm 
- stop vm 
- resize vdisk
- rollback vdisk 
u will get same error although that api response is 201 
```
 File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/49fc5356ac3092fc5e7e040537449d5e.py", line 225, in rollback
    raise j.exceptions.RuntimeError("Failed to run zeroctl restore {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl restore nil last hash Error: nil last hash
Usage:
  zeroctl restore vdisk id [flags]

Flags:
      --config SourceConfig        config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)
      --end-timestamp uint         end timestamp in nanosecond(default 0: until the end)
  -f, --force                      when given delete the vdisk if it already existed
  -h, --help                       help for vdisk
      --k int                      K variable of erasure encoding (default 4)
      --m int                      M variable of erasure encoding (default 2)
      --nonce string               hex nonce used for encryption (default "37b8e8a308c354048d245f6d")
      --priv-key string            private key (default "12345678901234567890123456789012")
      --start-timestamp uint       start timestamp in nanosecond(default 0: since beginning)
      --storage-addresses string   comma seperated list of redis compatible connectionstrings (format: '<ip>:<port>[@<db>]', eg: 'localhost:16379,localhost:6379@2'), if given, these are used for all vdisks, ignoring the given confi
g

Global Flags:
  -v, --verbose   log available information

 ((type:runtime.error)
[Wed16 13:52] - Job.py              :56  :j.core.jobcontroller.job.35e18ec418e72c0f437722c5e1e20e0c - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/49fc5356ac3092fc5e7e040537449d5e.py", line 346, in processChange
    j.tools.async.wrappers.sync(service.executeAction('rollback', args={'timestamp': args['timestamp']}, context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/49fc5356ac3092fc5e7e040537449d5e.py", line 225, in rollback
    raise j.exceptions.RuntimeError("Failed to run zeroctl restore {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl restore nil last hash Error: nil last hash
Usage:
  zeroctl restore vdisk id [flags]


```
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091

**Comment by khaledkbadr** [comment]
require some investigation on 0-Disk part https://github.com/zero-os/0-Disk/issues/425

**Comment by Dinaamagdy** [comment]
## Steps 
- create orch env as documented here in https://github.com/zero-os/0-orchestrator/tree/master/docs/setup 
- create two nodes with master 0-core in packet.net
- create blockcluster with 2 servers as shown : 
```
{
	"driveType": "ssd",
	"metaDriveType": "ssd",
	"clusterType": "block",
	"nodes": [
		"248a07e3cbf0"
	],
	"label": "st",
	"servers": 2
}
```

- create objectcluster with 2 servers
```
{
  "label": "ob",
  "servers": 2,
  "driveType": "ssd",
  "metaDriveType": "ssd",
  "nodes": [
    "248b07e3nof0"
  ],
  "clusterType": "object",
  "dataShards": 1,
  "parityShards": 1
}
```
- create vdisk with created  blockcluster and objectcluster as shown , it took 34 min to finish it's creation 
```
{
  "id": "vdisk",
  "size": 15,
  "blocksize": 4096,
  "type": "boot",
  "templatevdisk": "ardb:///template:ubuntu-1604",
  "blockStoragecluster": "st",
  "objectStoragecluster": "ob"
}
````
- create VM with vdisk as shown : 
```
{
	"id": "vmtest",
	"memory": 1024,
	"cpu": 48,
	"disks": [
		{
			"vdiskid": "vdisk",
			"maxIOps": 2000
		}
	],
	"userCloudInit": null,
	"systemCloudInit": null
}
```
- login inside vm and it took about 15 min to boot
- write newfile
- wait a mins 
- record timestamp A
- wait again 
- delete a file 
- wait again 
- stop vm 
- rollback to timestamp A , it took more than 40 min and jwt expired before it rollback request finished 
## Software Vesion 
0-0rchestrator :  ```vdisk-rollback``` branch commit 477506c3ff269b2068d643e5e5debf9a0227747e
js9: 9.1.2
0-disk flist : ```https://hub.gig.tech/khaledkbadr/0-disk-nbd-eol-experiment.flist```

**Comment by Dinaamagdy** [comment]
blocked due to https://github.com/zero-os/0-orchestrator/issues/1044

**Comment by Dinaamagdy** [comment]
## Software Version 
95169a2f3e3711b6daa39ec14a8a510eb4656e29
