### ISSUE TITLE
Delete /node/nodeid API doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#845]
## Steps 
- create 2 nodes 
- In node 1 create st and vm 
- Try to delete node 2 ,using Delete /nodes/nodeid Api
## Error 
```
2017-08-08 13:28:14 - (network)[INFO][127.0.0.1:51878]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/aysrun/de99521ac8d9a07a8ad9b75a11d0f8dd  200 447
INFO:network:
2017-08-08 13:28:15 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 157, in delete
    return await auth(request, ays_api.deleteServiceByName(request, name, role, repository))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 693, in deleteServiceByName
    await service.delete()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 365, in delete
    raise j.exceptions.RuntimeError(msg)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Can't remove service:node!0cc47aabae26 has children [service:storagepool!0cc47aabae26_fscache, service:container!vdisks_vm22_0cc47aabae26, service:container!vdisks_vm_0cc47aabae26, service:tcp!tcp_0cc47aabae26_11213, service:tcp!tcp_0cc47aabae26_11212, service:container!vdisks_vm11_0cc47aabae26, service:tcp!tcp_0cc47aabae26_11211]. ((type:runtime.error)

ERROR:sanic:Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 157, in delete
    return await auth(request, ays_api.deleteServiceByName(request, name, role, repository))
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 14, in auth
    return await func
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_api.py", line 693, in deleteServiceByName
    await service.delete()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 365, in delete
    raise j.exceptions.RuntimeError(msg)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Can't remove service:node!0cc47aabae26 has children [service:storagepool!0cc47aabae26_fscache, service:container!vdisks_vm22_0cc47aabae26, service:container!vdisks_vm_0cc47aabae26, service:tcp!tcp_0cc47aabae26_11213, service:tcp!tcp_0cc47aabae26_11212, service:container!vdisks_vm11_0cc47aabae26, service:tcp!tcp_0cc47aabae26_11211]. ((type:runtime.error)
```
## Software Version 
7c9ffb9d081915770442d3955223406bfaf73f03

**Comment by khaledkbadr** [comment]
Things needs to be implemented here

-  [ ] Prevent deletion of a node if it has storage cluster
-  [ ] Prevent deletion of storage cluster if it has vdiskstorage
-  [ ]  Prevent deletion of vdiskstorage if it has either vdisk or image
-  [ ]  Prevent deletion of vdisk if it's attached to VM
-  [ ]  Figure out how to deal with etcd_cluster servers when deleting the node

**Comment by ahmedelsayed-93** [comment]
still can't delete node

### ays error
```
[Tue14 11:15] - Job.py              :29  :j.core.jobcontroller.job.18c12c55009ed9bb751219f9cde7c7a3 - INFO     - job: node.zero-os!0cc47a740636 (uninstall) took 14.[2/1995]187439 sec to execute
[Tue14 11:15] - Job.py              :70  :j.core.jobcontroller.job.18c12c55009ed9bb751219f9cde7c7a3 - ERROR    - job: node.zero-os!0cc47a740636 (uninstall) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.zero-os/5d3b2f122c73d56e8b82ef820f40d84e.py", line 229, in uninstall
    if node_services > 1:
TypeError: unorderable types: list() > int()
```
### software versions
master : 5c7668358

**Comment by ahmedelsayed-93** [comment]
node is deleted but ays produced this error
```
[Wed15 07:01] - Recurring.py        :63  :j.atyourservice.server         - ERROR    - Error during job: 
[Wed15 07:01] - server.py           :527 :asyncio                        - ERROR    - Exception in callback <function RecurringTask.start.<locals>.callback at 0x7f2748153c80>
handle: <Handle RecurringTask.start.<locals>.callback>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48426)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Recurring.py", line 59, in callback
    future.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112750)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Recurring.py", line 86, in _run
    await self._job.execute()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110832)
  File "uvloop/future.pyx", line 434, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114064)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112715)
  File "/tmp/actions/node.zero-os/0d7742638d96125a8f101c4e579bcbaa.py", line 379, in streaming
    await check_node(job)
  File "/tmp/actions/node.zero-os/0d7742638d96125a8f101c4e579bcbaa.py", line 339, in check_node
    await cl.ping()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 135, in ping
    response = await self.sync('core.ping', {})
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 127, in sync
    response = await self.raw(command, args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 116, in raw
    self._redis = await self.get()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 82, in get
    timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/commands/__init__.py", line 148, in create_redis
    loop=loop)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/connection.py", line 78, in create_connection
    host, port, ssl=ssl, loop=loop), timeout, loop=loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
ERROR:asyncio:Exception in callback <function RecurringTask.start.<locals>.callback at 0x7f2748153c80>
handle: <Handle RecurringTask.start.<locals>.callback>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48426)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Recurring.py", line 59, in callback
    future.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112750)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Recurring.py", line 86, in _run
    await self._job.execute()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110832)
  File "uvloop/future.pyx", line 434, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114064)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112715)
  File "/tmp/actions/node.zero-os/0d7742638d96125a8f101c4e579bcbaa.py", line 379, in streaming
    await check_node(job)
  File "/tmp/actions/node.zero-os/0d7742638d96125a8f101c4e579bcbaa.py", line 339, in check_node
    await cl.ping()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 135, in ping
    response = await self.sync('core.ping', {})
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 127, in sync
    response = await self.raw(command, args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 116, in raw
    self._redis = await self.get()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Pubsub.py", line 82, in get
    timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/commands/__init__.py", line 148, in create_redis
    loop=loop)
  File "/usr/local/lib/python3.5/dist-packages/aioredis/connection.py", line 78, in create_connection
    host, port, ssl=ssl, loop=loop), timeout, loop=loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
