### ISSUE TITLE
Can't delete gateway

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#849]
## Issue 
when you try to delete created gw u will get this error : 
```
p 2 in run cf06517702b3396caf1c2bc9976374da
Error of job: gateway!test5 (uninstall):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/gateway/8414c50604acaa0d4361e13aec6a0ee5.py", line 115, in uninstall
    j.tools.async.wrappers.sync(container.delete())
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 365, in delete
    raise j.exceptions.RuntimeError(msg)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Can't remove service:container!test5 has children [service:http!test5, service:dhcp!test5, service:cloudinit!test5, service:firewall!test5]. ((type:runtime.error)
```
## Software Version 
00cb80349baf807d120799b0e37942a4dfac1b47

**Comment by grimpy** [comment]
Will be fixed as part of js9 we depend on

**Comment by Dinaamagdy** [comment]
## Software Verification 
ea6468df6151ab593f4ddab3ca304c8ef011ec71
