### ISSUE TITLE
Internal server error when create vdisk

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#872]
### ays log
```
[Sun13 11:14] - RunScheduler.py     :160 :j.ays.runscheduler             - INFO     - reschedule run 2fa75ac299e6e509d56db8660aac2300 in 30sec
[Sun13 11:14] - RunStep.py          :69  :j.atyourservice.server         - INFO     - execute job: vdisk!220ecb9628 (install)
[Sun13 11:14] - Job.py              :56  :j.core.jobcontroller.job.3c436700a66cb4ec1d4be96c90fb7764 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/5e5cbcb294d012dcea437e5dbdbee9e9.py", line 286, in install
    save_config(job)
  File "/tmp/actions/vdisk/5e5cbcb294d012dcea437e5dbdbee9e9.py", line 55, in save_config
    result = etcd.put(key="%s:vdisk:conf:static" % service.name, value=yamlconfig)
UnboundLocalError: local variable 'etcd' referenced before assignment
[Sun13 11:14] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Sun13 11:14] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run 4a132d40294096498b6c6fe46920974e
Error of job: vdisk!220ecb9628 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/5e5cbcb294d012dcea437e5dbdbee9e9.py", line 286, in install
    save_config(job)
  File "/tmp/actions/vdisk/5e5cbcb294d012dcea437e5dbdbee9e9.py", line 55, in save_config
    result = etcd.put(key="%s:vdisk:conf:static" % service.name, value=yamlconfig)
UnboundLocalError: local variable 'etcd' referenced before assignment
```

### software version
1.1.0-alpha-7 : 4608799

**Comment by ahmedelsayed-93** [comment]
### software version
1.1.0-alpha-7 : e86e4f147
