### ISSUE TITLE
OVS container not started after a reboot of a node

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#890]
```
[Wed16 13:11] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run fbd466193ee8fcf66a5363bb223f78ef
Error of job: container!geertsgw (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/5158dc504186be188012c7edd43e5bd1.py", line 50, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/5158dc504186be188012c7edd43e5bd1.py", line 152, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 206, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 177, in _create_container
    containerid = job.get(timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 990, in get
    raise Exception('failed to create container: %s' % result.data)
Exception: failed to create container: "ovs is needed for VXLAN network type"


******************************************************************************************
```

**Comment by grimpy** [comment]
https://github.com/zero-os/0-orchestrator/issues/704
