### ISSUE TITLE
Error in AYS run while deploying storage cluster

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#891]
Problem did not occur in the next retry of the run

```
[Wed16 13:32] - Job.py              :56  :j.core.jobcontroller.job.d37cefcf4a165aa5af618318c48e63d3 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_cluster/c889b6f3baee602a156ff5e20a271c01.py", line 72, in install
    save_config(job)
  File "/tmp/actions/storage_cluster/c889b6f3baee602a156ff5e20a271c01.py", line 341, in save_config
    result = etcd.put(key="%s:cluster:conf:storage" % service.name, value=yamlconfig)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/ETCD.py", line 89, in put
    return self.container.client.system(cmd, env={"ETCDCTL_API": "3"}).get()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 145, in client
    self._client = self.node.client.container.client(self.id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1150, in client
    self._client_chk.check(container)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 202, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 232, in _check
    return typ.check(object, t)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/typchk.py", line 82, in check
    raise t.reason('all branches failed')
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /
[Wed16 13:32] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 5: error
[Wed16 13:32] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 5 in run 87fbf526c7b0144469a69b2e1923f54f
Error of job: storage_cluster!geertsprimcluster (install):
*TRACEBACK*********************************************************************************
zeroos.core0.client.typchk.Tracker: [all branches failed] at -> /
  -> [invalid type, expecting <class 'int'>] at -> /
  -> [invalid type, expecting <class 'str'>] at -> /


******************************************************************************************
```

**Comment by grimpy** [comment]
Please provide a way to reproduce.

**Comment by khaledkbadr** [comment]
Right now the issue is not reproducible, as it happened from container client when an attempt to push configurations to `etcd` server using `etcdctl`. Now we use `etcd3` python client and all commands using the `container.client.system` has been replaced.

**Comment by Dinaamagdy** [comment]
can't reproduce in the current version 
## Software Version 
51ac26a298d1b861cd580cf952c1aa5860135d9e
