### ISSUE TITLE
Can't create gateway or container with nic type vlan / vxlan on packet.net machine nodes

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#892]
i followed this part in the documentation 
https://github.com/zero-os/0-orchestrator/tree/1.1.0-alpha-7/docs/setup#setup-the-backplane-network

#### configuration blueprint 
```yaml
configuration__main:
  configurations:
  - key: '0-core-version'
    value: '1.1.0-alpha-7'
  - key: 'js-version'
    value: '9.1.1'
  - key: 'gw-flist'
    value: 'https://hub.gig.tech/gig-official-apps/zero-os-gw-1.1.0-alpha-7.flist'
  - key: 'ovs-flist'
    value: 'https://hub.gig.tech/gig-official-apps/ovs-1.1.0-alpha-7.flist'
  - key: '0-disk-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-disk-1.1.0-alpha-7.flist'
  - key: 'jwt-token'
    value: '<jwt>'
  - key: 'jwt-key'
    value: 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv'
```
#### network blueprint 
```yaml
network.publicstorage__storage:
```

#### bootstrap
```yaml
bootstrap.zero-os__grid1:
  zerotierNetID: '<zerotier network id>'
  zerotierToken: '<zerotier token>'
  wipedisks: true
  networks:
    - storage

```

### api request 
![image](https://user-images.githubusercontent.com/24386820/29369043-b9778b86-82a1-11e7-90a5-0e9422bb07b8.png)

### ays log
```
Exception: failed to create container: "ovs is needed for VXLAN network type"
[Wed16 14:40] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Wed16 14:40] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run b0d7f81b03379065b52bc7227ac05252
Error of job: container!test-gw (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/47477c97b4ea3c55e1148258a1fff669.py", line 4, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/47477c97b4ea3c55e1148258a1fff669.py", line 127, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 206, in start
    self._create_container()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 177, in _create_container
    containerid = job.get(timeout)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 990, in get
    raise Exception('failed to create container: %s' % result.data)
Exception: failed to create container: "ovs is needed for VXLAN network type"
```

**we used to do create the ovs container manually using the core0 client using the following commands, and it was working fine**
```python
id = c.container.create( "https://hub.gig.tech/gig-official-apps/ovs.flist", host_network=True , tags=['ovs']).get()
ovs_client = c.container.client(id)
ovs_client.json('ovs.bridge-add', {"bridge": "backplane"})
ovs_client.json('ovs.vlan-ensure', {'master': 'backplane', 'vlan': 2000, 'name': 'vxbackend'})
```
but now once i execute the last command, the node leaves the zerotier.
### software version
1.1.0-alpha-7 : e86e4f1

**Comment by grimpy** [comment]
Seems it will never be possible to support this on top of packet.net as their private network is routed and thus we can not do broadcast which is required for vxlans to work.
