### ISSUE TITLE
machine stop,  always throughs an error on packet

### ISSUE THREAD

**Issue by ashraffouda** [zero-os/0-orchestrator#898]
container.client.job.kill(nbdserver_job_id) does not actually kill it. only happened on packet.net setup

*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/75ef1a1346e11ba55f05a40640070d96.py", line 744, in stop
    cleanupzerodisk(job)
  File "/tmp/actions/vm/75ef1a1346e11ba55f05a40640070d96.py", line 31, in cleanupzerodisk
    j.tools.async.wrappers.sync(nbdserver.executeAction('stop', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 723, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 748, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/nbdserver/0821bc1916b2f7571dfe674b0359df4a.py", line 202, in stop
    raise j.exceptions.RuntimeError("nbdserver didn't stopped")
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: nbdserver didn't stopped ((type:runtime.error)

**Comment by Dinaamagdy** [comment]
## Software Version 
eeaf1f7b491cabc0f99320338285b08d176f7e19
