### ISSUE TITLE
Can't delete node which has vm 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#912]
## Steps 
- create storage cluster in the node .
- create vdiskstorage and import image
- create VM in this node.
- try to delete this node.

## Error 
```
[Sun27 13:35] - Job.py              :56  :j.core.jobcontroller.job.708290164b4dbc8fbf094c4b0f1843d5 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storage_engine/12d92a8e60252b711d7280233a0f0518.py", line 138, in stop
    storageEngine.stop()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/StorageEngine.py", line 113, in stop
    raise RuntimeError("storage server {} didn't stopped")
RuntimeError: storage server {} didn't stopped
[Sun27 13:35] - Job.py              :66  :j.core.jo
```
## Software Version 
013d262e114f56599a0acaeb930d4f368ca32459

**Comment by FastGeert** [comment]
The error should be, cannot delete node, cause it has vms / storage components

**Comment by ahmedelsayed-93** [comment]
### software versions
master : 851d41fa
