### ISSUE TITLE
Create Vdisk with size multiple of 512 fail 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#926]
- Create vdisk with size 7* 512 as shown in payload give the following error 
```
{
  "id": "vdisk3",
  "size": 15,
  "blocksize": 3584,
  "type": "boot",
  "templatevdisk": "ardb:///template:ubuntu-1604",
  "blockStoragecluster": "st"
}
```
## Error 

```
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdisk/009f936b6acb5bfa3d09f54960259658.py", line 79, in install
    raise j.exceptions.RuntimeError("Failed to run zeroctl copy {} {}".format(result.stdout, result.stderr))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run zeroctl copy couldn't read source vdisk template:ubuntu-1604's static config: invalid config: blockSize '3584' is not a power of 2, while that is required t=2017-08-29T10:04:09+0000 lvl=eror msg="received invalid etcd config 'template:ubuntu-1604:vdisk:conf:static' (vdisk:'')" module=global caller=source_etcd.go:151
Error: couldn't read source vdisk template:ubuntu-1604's static config: invalid config: blockSize '3584' is not a power of 2, while that is required
Usage:
  zeroctl copy vdisk source_vdiskid target_vdiskid [target_clusterid] [flags]

Flags:
      --config SourceConfig   config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)
  -h, --help                  help for vdisk
      --same                  enable flag to force copy within the same nbd servers

Global Flags:
  -v, --verbose   log available information

 ((type:runtime.error)
```
## Software Version 
5d71c78faa37c0316e4d5f2143e9e6096d8f7fa9

**Comment by khaledkbadr** [comment]
@GlenDC What're the constraints that should be added for the blocksize?

**Comment by GlenDC** [comment]
@khaledkbadr the block size of all vdisks is given in bytes and **has to be a power of 2**, and **be 512 or greater**. I think that second rule of the rule isn't mentioned anywhere in the `/docs` folder documentation. But the first rule was already mentioned in https://github.com/zero-os/0-Disk/blob/master/docs/config.md#VdiskStaticConfig. Will also add the second rule to the documentation as well, but the first rule answers your question :)

The error message says the same as the documentation though: `blockSize '3584' is not a power of 2, while that is required`, so I would have though that is also clear enough in case you didn't read the documentation.

The second rule (**be 512 or greater**) is not as important and if for some reason you want vdisks to have a lower block size (e.g. 32, 64, 128, 256) I can change that, but it seemed unrealistic to me you would want that. However feel free to create a feature request issue for it if you would ever be in need of it.

The first rule (**has to be a power of 2**) however has certain implications and I would rather keep it that way. I didn't think it would be an issue as AFAIK block sizes are in our world always expressed in powers of 2. On top of that it's a rule that allows us to take it as an assumption, allowing us to keep code much simpler in certain places.

Failing to adhere to any of both rules will prevent you from mounting the vdisk.

**Comment by GlenDC** [comment]
Why you re-open this @khaledkbadr? What is not answered about this question?

**Comment by khaledkbadr** [comment]
In orchestrator we put tag question to mark the issue  as it's required more info, not that it always should be of the type question in itself. This issue still needs to be done in the orchestrator API to return 400 if the blocksize was not a power of 2

**Comment by GlenDC** [comment]
> This issue still needs to be done in the orchestrator API to return 400 if the blocksize was not a power of 2

Don't forget that it also has to be at least 512 (on top of having to be a power of 2). In theory we could handle block sizes as small as 2, but 512 seemed me already like a very small block size that I made the minimum 512 instead of 2.
