### ISSUE TITLE
Install script fail to start caddy 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#932]
## Steps 
use this installation  script https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh  
## Error 
```
[-] line 264: unexpected error
```

```
ource /root/.jsenv.sh; tmux capture-pane -pS -5000 -J
Traceback (most recent call last):
  File "/usr/local/bin/js9", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/jumpscale/core9/cmds/js9", line 19, in <module>
    exec(toexec)
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/apps/PrefabCaddy.py", line 164, in start
    "caddy", 'ulimit -n 8192; %s -conf=%s %s' % (cmd, configpath, agree), wait=1, expect=expect)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabProcessManager.py", line 317, in ensure
    self.prefab.tmux.executeInScreen("main", name, cmd, wait=wait, expect=expect)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabTmux.py", line 164, in executeInScreen
    rc, out = checkOutput()
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabTmux.py", line 153, in checkOutput
    raise j.exceptions.RuntimeError(msg)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Could not execute cmd:ulimit -n 8192; /opt/jumpscale9/bin/caddy -conf=/optvar/cfg/caddy.cfg  -agree
Out/Err:
**START**
2017/08/30 06:46:24 address fc7b:8774:61df:dbad:318d:0000:0000:0001:443:: too many colons in address

(js9) root@js9:~/gig/code/github/zero-os/0-orchestrator/api#

 ((type:runtime.error)
Could not execute cmd:ulimit -n 8192; /opt/jumpscale9/bin/caddy -conf=/optvar/cfg/caddy.cfg  -agree
Out/Err:
**START**
2017/08/30 06:46:24 address fc7b:8774:61df:dbad:318d:0000:0000:0001:443:: too many colons in address
```

**Comment by Dinaamagdy** [comment]
the problem was in zerotier , as I enable ipv6
