### ISSUE TITLE
migrating vm api request returns error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#978]
### API
```POST /nodes/{nodeid}/vms/{vmid}/migrate```
### request and response
![image](https://user-images.githubusercontent.com/24386820/30107822-345a2a8e-9300-11e7-8a30-feb044e70d7b.png)

###  orchestrator server log
```
172.29.9.115 - - [06/Sep/2017:10:28:48 +0000] "POST /nodes/248a07e3cbe0/vms HTTP/1.1" 201 0
2017/09/06 10:32:09 http: panic serving 172.29.9.115:50100: interface conversion: error is *json.SyntaxError, not tools.HTTPError
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc4203fc000)
        /opt/jumpscale9/go/root/src/net/http/server.go:1721 +0xd0
panic(0x8a88e0, 0xc4201bad40)
        /opt/jumpscale9/go/root/src/runtime/panic.go:489 +0x2cf
github.com/zero-os/0-orchestrator/api/tools.HandleExecuteBlueprintResponse(0xb51000, 0xc4203088e0, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc4203f9c20, 0x2f, 0x2f)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/http.go:59 +0x153
github.com/zero-os/0-orchestrator/api/node.NodeAPI.MigrateVM(0x7fff1d8b6a6e, 0x13, 0x7fff1d8b6a4d, 0x15, 0xc42000e1d8, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_api_MigrateVM.go:69 +0x7aa
github.com/zero-os/0-orchestrator/api/node.(*NodeAPI).MigrateVM(0xc4200fac30, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420144700)
        <autogenerated>:150 +0x87
github.com/zero-os/0-orchestrator/api/node.(NodesInterface).MigrateVM-fm(0x7f9be639c0e8, 0xc4203f9dd0, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_if.go:421 +0x50
net/http.HandlerFunc.ServeHTTP(0xc420347080, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420144700)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054aa0, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/zero-os/0-orchestrator/api/tools.(*Oauth2itsyouonlineMiddleware).Handler.func1(0x7f9be639c0e8, 0xc4203f9dd0, 0xc420407100)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/oauth2_itsyouonline_middleware.go:124 +0x253
net/http.HandlerFunc.ServeHTTP(0xc4200c1f60, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420407100)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420158200, 0x7f9be639c0e8, 0xc4203f9dd0, 0xc420407000)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:68 +0x117
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb51f80, 0xc42000e020, 0xb511c0, 0xc420158200, 0xb569c0, 0xc4200e81c0, 0xc420407000)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc4200c1f80, 0xb569c0, 0xc4200e81c0, 0xc420407000)
        <autogenerated>:8 +0x86
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054a50, 0xb569c0, 0xc4200e81c0, 0xc420407000)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc4202318c0, 0xb569c0, 0xc4200e81c0, 0xc420406e00)
        /opt/jumpscale9/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4203fc000, 0xb57280, 0xc420172080)
        /opt/jumpscale9/go/root/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /opt/jumpscale9/go/root/src/net/http/server.go:2668 +0x2ce
2017/09/06 10:32:16 http: panic serving 172.29.9.115:50470: interface conversion: error is *json.SyntaxError, not tools.HTTPError
goroutine 85 [running]:
net/http.(*conn).serve.func1(0xc4201b0140)
        /opt/jumpscale9/go/root/src/net/http/server.go:1721 +0xd0
panic(0x8a88e0, 0xc42029e440)
        /opt/jumpscale9/go/root/src/runtime/panic.go:489 +0x2cf
github.com/zero-os/0-orchestrator/api/tools.HandleExecuteBlueprintResponse(0xb51000, 0xc420278520, 0x7f9be639c0e8, 0xc4200fab40, 0xc4200fa000, 0x2f, 0x2f)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/http.go:59 +0x153
github.com/zero-os/0-orchestrator/api/node.NodeAPI.MigrateVM(0x7fff1d8b6a6e, 0x13, 0x7fff1d8b6a4d, 0x15, 0xc42000e1d8, 0x7f9be639c0e8, 0xc4200fab40, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_api_MigrateVM.go:69 +0x7aa
github.com/zero-os/0-orchestrator/api/node.(*NodeAPI).MigrateVM(0xc4200fac30, 0x7f9be639c0e8, 0xc4200fab40, 0xc420144700)
        <autogenerated>:150 +0x87
github.com/zero-os/0-orchestrator/api/node.(NodesInterface).MigrateVM-fm(0x7f9be639c0e8, 0xc4200fab40, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/node/node_if.go:421 +0x50
net/http.HandlerFunc.ServeHTTP(0xc420347080, 0x7f9be639c0e8, 0xc4200fab40, 0xc420144700)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054aa0, 0x7f9be639c0e8, 0xc4200fab40, 0xc420144700)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/zero-os/0-orchestrator/api/tools.(*Oauth2itsyouonlineMiddleware).Handler.func1(0x7f9be639c0e8, 0xc4200fab40, 0xc42000ae00)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/oauth2_itsyouonline_middleware.go:124 +0x253
net/http.HandlerFunc.ServeHTTP(0xc4200c1f60, 0x7f9be639c0e8, 0xc4200fab40, 0xc42000ae00)
        /opt/jumpscale9/go/root/src/net/http/server.go:1942 +0x44
github.com/zero-os/0-orchestrator/api/tools.(*connectionMiddleware).ServeHTTP(0xc420158200, 0x7f9be639c0e8, 0xc4200fab40, 0xc42000ac00)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/tools/connection.go:68 +0x117
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb51f80, 0xc42000e020, 0xb511c0, 0xc420158200, 0xb569c0, 0xc4200e8380, 0xc42000ac00)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc4200c1f80, 0xb569c0, 0xc4200e8380, 0xc42000ac00)
        <autogenerated>:8 +0x86
github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054a50, 0xb569c0, 0xc4200e8380, 0xc42000ac00)
        /opt/jumpscale9/go/proj/src/github.com/zero-os/0-orchestrator/api/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc4202318c0, 0xb569c0, 0xc4200e8380, 0xc42000a900)
        /opt/jumpscale9/go/root/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201b0140, 0xb57280, 0xc420158500)
        /opt/jumpscale9/go/root/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /opt/jumpscale9/go/root/src/net/http/server.go:2668 +0x2ce
```

### ays log
```
2017-09-06 10:32:14 - (network)[INFO][127.0.0.1:34008]: POST http://127.0.0.1:5000/ays/repository/orchestrator-server/blueprint/vm_2-vm_migrate_1504693932  200 112
INFO:network:
[Wed06 10:32] - Job.py              :56  :j.core.jobcontroller.job.ee730751dd0f7d289118c8e36b152a71 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/6e8996af8f2ee5f23c265939a74f395e.py", line 771, in processChange
    update_data(job, args)
  File "/tmp/actions/vm/6e8996af8f2ee5f23c265939a74f395e.py", line 90, in update_data
    j.tools.async.wrappers.sync(job.execute())
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py", line 357, in execute
    self.save()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/jobcontroller/Job.py", line 299, in save
    self.service.saveAll()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 332, in saveAll
    self.saveToFS()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 317, in saveToFS
    j.sal.fs.writeFile(path2, self.model.dictJson, append=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 1289, in writeFile
    fp.close()
OSError: [Errno 9] Bad file descriptor
```
### software version
master 54b5700

**Comment by Dinaamagdy** [comment]
it return this error now
```
[Thu07 09:08] - Job.py              :66  :j.core.jobcontroller.job.b9490a934a1a51892577854ea42aea7e - INFO     - job job: tcp!migrationtcp_0cc47ad6676a_4001 (drop) done sucessfuly
[Thu07 09:08] - Job.py              :56  :j.core.jobcontroller.job.dafc79f63ec1bd06653af97ca9a78f3b - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/5f9e3790413bf6bbb64e17cf70fd1474.py", line 257, in processChange
    update_data(job, args)
  File "/tmp/actions/vm/5f9e3790413bf6bbb64e17cf70fd1474.py", line 393, in update_data
    migrate(job)
  File "/tmp/actions/vm/5f9e3790413bf6bbb64e17cf70fd1474.py", line 160, in migrate
    ssh_port, job_id = start_migartion_channel(job, old_node, target_node)
  File "/tmp/actions/vm/5f9e3790413bf6bbb64e17cf70fd1474.py", line 563, in start_migartion_channel
    raise e
  File "/tmp/actions/vm/5f9e3790413bf6bbb64e17cf70fd1474.py", line 512, in start_migartion_channel
    node.name))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to run ssh instance to migrate vm from0cc47a740636_0cc47ad6676a ((type:runtime.error)
2017-09-07 09:08:49 - (network)[INFO][127.0.0.1:45520]: GET http://127.0.0.1:5000/ays/repository/orchestrator-server/job/dafc79f63ec1bd06653af97ca9a78f3b  200 1569
INFO:network:

```

**Comment by ahmedelsayed-93** [comment]
the api response still returns nothing, no response code, headers or data

**Comment by rkhamis** [comment]
Seems like an error is raised indeed here: https://github.com/zero-os/0-orchestrator/blob/ef9ff090dff21a7022a36409d2a0cd282c356985/templates/vm/actions.py#L427

Investigating why response is incomplete from the AYS side

**Comment by rkhamis** [comment]
No. Orchestrator side

**Comment by rkhamis** [comment]
Casting here is the issue: https://github.com/zero-os/0-orchestrator/blob/1c34c11eb9430508b981d8b81f4261708623fb21/api/tools/http.go#L59

**Comment by Dinaamagdy** [comment]
## Software Version 
e464e04553b4b64fc24e738931e055e93d6b97e4
