### ISSUE TITLE
internal server error when shutdown vm

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#982]
```
INFO:network:
[Wed06 13:02] - Job.py              :56  :j.core.jobcontroller.job.c57438c62182a0c2984d8230a6eb4383 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/37f58f1c84f49501cf92acb98795c6ba.py", line 70, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to shutdown vm de3d194cff ((type:runtime.error)
[Wed06 13:02] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Wed06 13:02] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run e4fee1d6c551b9686ebd3693c8514a0c
Error of job: vm!de3d194cff (shutdown):
*TRACEBACK*********************************************************************************
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to shutdown vm de3d194cff ((type:runtime.error)
```

### software version
master c0d5c45d

**Comment by ahmedelsayed-93** [comment]
issue still exists
```
[Thu07 14:46] - Job.py              :56  :j.core.jobcontroller.job.db89bf072c020d8df5fd26e591d635ac - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/14a5ddf1116bf0fc774fef4d953cbcc9.py", line 636, in shutdown
    raise j.exceptions.RuntimeError("Failed to shutdown vm {}".format(service.name))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to shutdown vm 6eb6cdbdcb ((type:runtime.error)
[Thu07 14:46] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 1: error
[Thu07 14:46] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of step 1 in run a9a26e3e11004dc852f52684eb4a8444
Error of job: vm!6eb6cdbdcb (shutdown):
*TRACEBACK*********************************************************************************
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Failed to shutdown vm 6eb6cdbdcb ((type:runtime.error)
```
### software version
master  3a7c7d9

**Comment by rkhamis** [comment]
Are we sure that the vm is booted before being shutdown?

**Comment by FastGeert** [comment]
Good remark, but even then we should not throw an error.

**Comment by ahmedelsayed-93** [comment]
@rkhamis @FastGeert 
it works now if the vm is booted before shutdown, else it returns internal server error but the vm will be halted correctly

**Comment by rkhamis** [comment]
created a bug for this here: https://github.com/zero-os/0-orchestrator/issues/994

**Comment by islamTaha12** [comment]
normal shutdown is working nw but we still have this special case #994
